# -*- coding: utf-8 -*-
"""G2-04 independent event-log replay checker (E2) for the G2-03 deterministic DES.

Role
----
This module is the INDEPENDENT log-replay checker (E2) for task package
G2-03-SPEC-V1.0.2 (G2-04 task: CR-V3.1 C08/C09/C10/C11/C12/C17/C18/C19/C20/C21
replay side).  It takes ONLY the immutable ``event_log`` (append-only JSONL /
JSON array), the frozen ``des_config``, the scripted fixture record, the
shared ``parameters.csv`` and (optionally) the run ``metrics`` block, and
INDEPENDENTLY recomputes every quantity that the frozen event_log_contract
requires:

  * bay occupancy coverage ``[0, T)`` per bay (device residency + physical
    turnover; 0.5h_overlap zero-duration IN folding rule),
  * A/B/C/E resource occupancy (capacity-1 BUSY intervals; IDLE elsewhere),
  * task release / start / end per (device, process, effective_attempt_no),
  * release_time frozenness (K9: device3 B retest release constant 8.5 h = 51
    ticks across the shift change),
  * effective_attempt_no advancement (cancelled fragments never advance; 1<2),
  * test outcome PASS/ABNORMAL vs the scripted outcomes (a completed effective
    test without a scripted outcome is an explicit MISSING_SCRIPTED_OUTCOME
    failure),
  * cancel reason (DEVICE_EXIT / SHIFT_INTERRUPT),
  * shift boundaries (SHIFT_CHANGE events + half-open intervals; completions
    settle before the shift change),
  * turnover phases (OUT_START/OUT_COMPLETE/IN_START/IN_COMPLETE + bay; the
    last device is never transported out),
  * device terminal state (PASSED/EXITED + terminal_reason) and D
    materialization timing (E2: at the A/B/C all-PASS timestamp, before the E
    TASK_RELEASE, never at the E ACTIVITY_START, never regenerated by an E
    retest, early-exit devices keep not_created),
  * T (the last terminal-judgment time == SIMULATION_END time),
  * the YXB / age ledger seam (per-process elapsed_hours sums incl. cancelled
    fragments, divided by shift_count * shift_length),
  * the frozen same-timestamp closure order (settle -> observe -> classify ->
    exit -> cancel -> E2 D -> shift -> release -> dispatch -> liveness),
  * the frozen acceptance values (T/S/PL/PW and the K9 YXB block) and the
    optional run metrics block.

Isolation (CR-V3.1/C19)
-----------------------
This module imports ONLY the Python standard library.  It NEVER imports,
reads, or executes anything under ``04_代码/main_model/`` (the main DES
engine), never imports other checker modules, never imports test modules and
never launches the main engine as a child process.  Its only inputs are the
immutable event_log, the frozen config, the scripted fixture, the shared
parameters.csv and the optional metrics block.  The static/dynamic isolation
proof lives in ``04_代码/tests/test_des_checker_v1.py``.

Time representation
-------------------
Every canonical time is an exact ``fractions.Fraction`` (parsed from decimal
or fraction strings; floats are explicitly rejected).  1 tick = 10 min =
1/6 h (G2-03-SPEC-V1.0.2 §9b.integer_time_scaling); every canonical time must
satisfy tick*6 being an integer (NonIntegerTickError otherwise).  All activity
intervals are half-open ``[start, end)``.

0.5h_overlap folding rule (V1.0.2)
----------------------------------
For the isolated ``0.5h_overlap`` profile the log may record
TURNOVER_OUT_START at ``t0`` and TURNOVER_OUT_COMPLETE / TURNOVER_IN_START /
TURNOVER_IN_COMPLETE all at ``t0 + 0.5h`` (zero-duration IN log
representation).  The physical bay occupancy is strictly ``[t0, t0 + 0.5h)``;
the checker folds the zero-length IN representation and never double-counts
bay occupancy.

Exit codes (CLI): 0 PASS, 1 FAIL (checker found differences), 2 validation
error (bad input), 3 checker internal failure, 4 file I/O.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from dataclasses import dataclass, field
from fractions import Fraction
from typing import Any, Optional

# ---------------------------------------------------------------------------
# Frozen constants (G2-03-SPEC-V1.0.2 / shared schema)
# ---------------------------------------------------------------------------

TICKS_PER_HOUR = 6  # 1 tick = 10 min = 1/6 h
PROCESSES = ("A", "B", "C", "E")
PROCESS_ORDER = {"A": 0, "B": 1, "C": 2, "E": 3}
BAY_IDS = (1, 2)
CANCEL_REASONS = ("DEVICE_EXIT", "SHIFT_INTERRUPT")
TERMINAL_REASON_SECOND_ABNORMAL = "process_second_abnormal"

EVENT_TYPES = frozenset({
    "ACTIVITY_START", "ACTIVITY_COMPLETE", "OBSERVATION_MATERIALIZED",
    "D_CREATED", "TASK_RELEASE", "DEVICE_EXIT", "TASK_CANCEL",
    "TURNOVER_OUT_START", "TURNOVER_OUT_COMPLETE", "TURNOVER_IN_START",
    "TURNOVER_IN_COMPLETE", "SHIFT_CHANGE", "WAKE_UP", "DEVICE_TERMINAL",
    "SIMULATION_END",
})

# Per-event-type required fields (mirrors src/schemas/des_event_log_v1.schema.json).
REQUIRED_FIELDS: dict[str, tuple[str, ...]] = {
    "ACTIVITY_START": ("device_id", "process", "effective_attempt_no",
                       "resource_id", "bay_id", "squad_id",
                       "attempt_start_time", "attempt_end_time", "release_time"),
    "ACTIVITY_COMPLETE": ("device_id", "process", "effective_attempt_no",
                          "resource_id", "bay_id", "attempt_start_time",
                          "attempt_end_time", "elapsed_hours"),
    "OBSERVATION_MATERIALIZED": ("device_id", "process", "effective_attempt_no",
                                 "outcome"),
    "D_CREATED": ("device_id", "d_state"),
    "TASK_RELEASE": ("device_id", "process", "effective_attempt_no", "release_time"),
    "DEVICE_EXIT": ("device_id",),
    "TASK_CANCEL": ("device_id", "process", "effective_attempt_no",
                    "cancel_reason", "outcome"),
    "TURNOVER_OUT_START": ("bay_id",),
    "TURNOVER_OUT_COMPLETE": ("bay_id",),
    "TURNOVER_IN_START": ("bay_id",),
    "TURNOVER_IN_COMPLETE": ("bay_id",),
    "SHIFT_CHANGE": ("shift_index", "shift_start", "shift_end", "on_duty_squad"),
    "WAKE_UP": (),
    "DEVICE_TERMINAL": ("device_id", "terminal_state"),
    "SIMULATION_END": (),
}

TIME_FIELDS = ("event_time", "attempt_start_time", "attempt_end_time",
               "release_time", "elapsed_hours", "shift_start", "shift_end")

REGISTRY_VERSION = "CR-V3.1"
CHECK_IDS = ("C08", "C09", "C10", "C11", "C12", "C17", "C18", "C19", "C20", "C21")


# ---------------------------------------------------------------------------
# Errors and exact time helpers
# ---------------------------------------------------------------------------


class CheckerError(Exception):
    """Base class for checker failures."""


class CheckerValidationError(CheckerError):
    """Invalid input (config / fixture / log envelope); CLI exit 2."""


class NonIntegerTickError(CheckerError):
    """A canonical time is not an integer multiple of 1/6 h (explicit FAIL)."""


class CheckerNumericalError(CheckerError):
    """Checker-internal numerical failure; CLI exit 3."""


def parse_hours(value: Any, ctx: str = "time") -> Fraction:
    """Parse a canonical time exactly.  Floats/bools are explicitly rejected."""
    if isinstance(value, bool):
        raise CheckerValidationError("%s: boolean is not a rational time: %r" % (ctx, value))
    if isinstance(value, float):
        raise CheckerValidationError(
            "%s: float is forbidden as canonical time: %r (use exact strings)" % (ctx, value))
    if isinstance(value, int):
        return Fraction(value)
    if isinstance(value, Fraction):
        return value
    if isinstance(value, str):
        text = value.strip()
        if not text:
            raise CheckerValidationError("%s: empty time string" % ctx)
        try:
            return Fraction(text)
        except (ValueError, ZeroDivisionError) as exc:
            raise CheckerValidationError(
                "%s: not a valid rational string: %r" % (ctx, value)) from exc
    raise CheckerValidationError(
        "%s: unsupported time type %s: %r" % (ctx, type(value).__name__, value))


def hours_to_ticks(value: Any, ctx: str = "time") -> int:
    """Hours -> integer ticks; fails explicitly when not a 1/6 h multiple."""
    f = parse_hours(value, ctx)
    ticks = f * TICKS_PER_HOUR
    if ticks.denominator != 1:
        raise NonIntegerTickError(
            "%s: %s h is not an integer multiple of 1/6 h (= %s ticks)" % (ctx, f, ticks))
    return int(ticks)


def frac_to_str(f: Fraction) -> str:
    """Fraction -> exact string (integer form when denominator == 1)."""
    f = Fraction(f)
    if f.denominator == 1:
        return str(f.numerator)
    return "%d/%d" % (f.numerator, f.denominator)


def fmt_opt(f: Optional[Fraction]) -> Optional[str]:
    return None if f is None else frac_to_str(f)


# ---------------------------------------------------------------------------
# Shared parameters (parameters.csv) loader (stdlib-only)
# ---------------------------------------------------------------------------

_PARA_FIELDS = {
    "P001": "machine_count",
    "P002": "capacity_A",
    "P003": "capacity_B",
    "P004": "capacity_C",
    "P005": "capacity_E",
    "P006": "test_duration_A",
    "P007": "test_duration_B",
    "P008": "test_duration_C",
    "P009": "test_duration_E",
    "P014": "transport_out",
    "P015": "transport_in",
    "P037": "batch_size_q2",
    "P040": "batch_size_q3",
    "P059": "turnover_duration_literal",
    "P061": "key_schema",
}


def load_parameters(path: Optional[str]) -> dict[str, str]:
    """Read parameters.csv into {code_name: value} (shared read-only input)."""
    out: dict[str, str] = {}
    if path is None:
        return out
    try:
        with open(path, "r", encoding="utf-8-sig", newline="") as handle:
            reader = csv.DictReader(handle)
            for row in reader:
                pid = (row.get("parameter_id") or "").strip()
                if pid in _PARA_FIELDS:
                    out[_PARA_FIELDS[pid]] = (row.get("value") or "").strip()
    except OSError as exc:
        raise CheckerValidationError("cannot read parameters.csv: %s" % exc) from exc
    return out


# ---------------------------------------------------------------------------
# Report structures
# ---------------------------------------------------------------------------


@dataclass
class CheckIssue:
    """One precise difference found by the checker."""

    check_id: str
    location: str
    expected: Any
    actual: Any
    message: str

    def to_dict(self) -> dict:
        return {
            "check_id": self.check_id,
            "location": self.location,
            "expected": _json_safe(self.expected),
            "actual": _json_safe(self.actual),
            "message": self.message,
        }

    def describe(self) -> str:
        return "[%s] %s: %s (expected=%r, actual=%r)" % (
            self.check_id, self.location, self.message,
            _json_safe(self.expected), _json_safe(self.actual))


def _json_safe(value: Any) -> Any:
    if isinstance(value, Fraction):
        return frac_to_str(value)
    if isinstance(value, tuple):
        return [_json_safe(v) for v in value]
    if isinstance(value, list):
        return [_json_safe(v) for v in value]
    if isinstance(value, dict):
        return {str(k): _json_safe(v) for k, v in value.items()}
    return value


@dataclass
class CheckReport:
    """Deterministic report of one checker run."""

    fixture_id: str
    scenario_id: str
    verdict: str  # PASS | FAIL
    issues: list[CheckIssue] = field(default_factory=list)
    special_assertions: list[dict] = field(default_factory=list)
    recomputed: dict[str, Any] = field(default_factory=dict)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "envelope_type": "des_check_report",
            "schema_version": "des_check_report_v1",
            "registry_version": REGISTRY_VERSION,
            "fixture_id": self.fixture_id,
            "scenario_id": self.scenario_id,
            "verdict": self.verdict,
            "issues": [i.to_dict() for i in self.issues],
            "special_assertions": _json_safe(self.special_assertions),
            "recomputed": _json_safe(self.recomputed),
            "metadata": _json_safe(self.metadata),
        }

    def summarize(self) -> str:
        return "%s %s T=%s ticks=%s %s (%d issues)" % (
            self.fixture_id,
            self.scenario_id,
            self.recomputed.get("T_h"),
            self.recomputed.get("T_ticks"),
            self.verdict,
            len(self.issues),
        )


# ---------------------------------------------------------------------------
# The independent checker
# ---------------------------------------------------------------------------


class DesEventLogChecker:
    """Replays an immutable event_log and independently recomputes all frozen
    replay quantities, comparing them against internal invariants, the
    scripted fixture, the frozen config/parameters and (optionally) the run
    metrics / frozen acceptance block."""

    def __init__(self, event_log: Any, config: dict, scripted: dict,
                 parameters: Optional[str] = None,
                 metrics: Optional[dict] = None) -> None:
        self._issues: list[CheckIssue] = []
        self._special: list[dict] = []
        self._recomputed: dict[str, Any] = {}
        self._cfg = self._parse_config(config)
        self._scripted_outcomes: dict[tuple, str] = {}
        self._real_states: dict[int, dict[str, str]] = {}
        self._acceptance: Optional[dict] = None
        self._fixture_id = self._parse_scripted(scripted)
        self._parameters = load_parameters(parameters)
        self._metrics = metrics if isinstance(metrics, dict) else None
        self._log, self._structural_ok = self._parse_event_log(event_log)

        # replay views (built lazily by run())
        self._records_by_type: dict[str, list[dict]] = {}
        self._tasks: dict[tuple, dict[str, Any]] = {}
        self._devices: dict[int, dict[str, Any]] = {}
        self._shifts: list[dict] = []
        self._turnovers: list[dict] = []
        self._T: Optional[Fraction] = None

    # ------------------------------------------------------------------
    # input parsing
    # ------------------------------------------------------------------

    def _parse_config(self, raw: dict) -> dict:
        if not isinstance(raw, dict):
            raise CheckerValidationError("config must be a JSON object")
        if raw.get("schema_version") != "des_config_v1":
            raise CheckerValidationError("config.schema_version must be 'des_config_v1'")
        if raw.get("random_enabled") is not False:
            raise CheckerValidationError("G2-03 is deterministic: random_enabled must be false")
        scenario = raw.get("scenario")
        if scenario not in ("q2_single_shift", "q3_two_shift", "isolated_small_case"):
            raise CheckerValidationError("config.scenario invalid: %r" % (scenario,))
        batch_size = raw.get("batch_size")
        if not isinstance(batch_size, int) or batch_size < 1:
            raise CheckerValidationError("config.batch_size must be a positive integer")
        shift_length = parse_hours(raw.get("shift_length_h"), "config.shift_length_h")
        if shift_length <= 0:
            raise CheckerValidationError("config.shift_length_h must be positive")
        shifts_per_day = raw.get("shifts_per_day")
        if not isinstance(shifts_per_day, int) or shifts_per_day < 1:
            raise CheckerValidationError("config.shifts_per_day must be a positive integer")
        durations_raw = raw.get("durations")
        if not isinstance(durations_raw, dict):
            raise CheckerValidationError("config.durations must be an object")
        durations: dict[str, Fraction] = {}
        for proc in PROCESSES:
            if proc not in durations_raw:
                raise CheckerValidationError("config.durations missing process %s" % proc)
            durations[proc] = parse_hours(durations_raw[proc], "config.durations.%s" % proc)
            if durations[proc] <= 0:
                raise CheckerValidationError("config.durations.%s must be positive" % proc)
        transport_out = parse_hours(raw.get("transport_out_h"), "config.transport_out_h")
        transport_in = parse_hours(raw.get("transport_in_h"), "config.transport_in_h")
        if transport_out < 0 or transport_in < 0:
            raise CheckerValidationError("transport durations must be non-negative")
        profile = raw.get("turnover_profile")
        if profile not in ("1h_literal", "0.5h_overlap"):
            raise CheckerValidationError("config.turnover_profile invalid: %r" % (profile,))
        if raw.get("key_schema_version") != "key_schema_v1":
            raise CheckerValidationError("config.key_schema_version must be 'key_schema_v1'")
        initial = raw.get("deterministic_initial_state")
        if not isinstance(initial, dict):
            raise CheckerValidationError("config.deterministic_initial_state must be an object")
        if initial.get("all_calibrated") is not True or initial.get("queues_empty") is not True:
            raise CheckerValidationError(
                "deterministic_initial_state.all_calibrated/queues_empty must be true")
        preloaded = initial.get("preloaded_devices")
        if not isinstance(preloaded, list) or not preloaded:
            raise CheckerValidationError("deterministic_initial_state.preloaded_devices invalid")
        expected_preload = [1] if batch_size == 1 else [1, 2]
        if list(preloaded) != expected_preload:
            raise CheckerValidationError(
                "SEM-21 initial-state rule: batch_size==%d requires preloaded_devices == %r, got %r"
                % (batch_size, expected_preload, list(preloaded)))
        # durations must be integer ticks (contract: tick*6 integer)
        for proc in PROCESSES:
            hours_to_ticks(durations[proc], "config.durations.%s" % proc)
        hours_to_ticks(transport_out, "config.transport_out_h")
        hours_to_ticks(transport_in, "config.transport_in_h")
        return {
            "scenario_id": raw.get("scenario_id") or "",
            "scenario": scenario,
            "batch_size": batch_size,
            "shift_length_h": shift_length,
            "shifts_per_day": shifts_per_day,
            "durations": durations,
            "transport_out_h": transport_out,
            "transport_in_h": transport_in,
            "turnover_profile": profile,
            "preloaded_devices": tuple(preloaded),
            "random_enabled": False,
            "key_schema_version": "key_schema_v1",
        }

    def _parse_scripted(self, raw: dict) -> str:
        if not isinstance(raw, dict):
            raise CheckerValidationError("scripted fixture must be a JSON object")
        fixture_id = raw.get("fixture_id")
        if not isinstance(fixture_id, str) or not fixture_id:
            raise CheckerValidationError("scripted fixture needs a non-empty fixture_id")
        outcomes_raw = raw.get("scripted_outcomes")
        if not isinstance(outcomes_raw, list):
            raise CheckerValidationError("scripted_outcomes must be a list")
        self._scripted_outcomes = {}
        for item in outcomes_raw:
            if not isinstance(item, dict):
                raise CheckerValidationError("scripted_outcomes items must be objects")
            device_id = item.get("device_id")
            process = item.get("process")
            attempt = item.get("effective_attempt_no")
            outcome = item.get("outcome")
            if not isinstance(device_id, int) or process not in PROCESSES \
                    or attempt not in (1, 2) or outcome not in ("PASS", "ABNORMAL"):
                raise CheckerValidationError("bad scripted outcome item: %r" % (item,))
            key = (device_id, process, attempt)
            if key in self._scripted_outcomes:
                raise CheckerValidationError("duplicate scripted outcome %r" % (key,))
            self._scripted_outcomes[key] = outcome
        real_raw = raw.get("scripted_real_states")
        if not isinstance(real_raw, dict):
            raise CheckerValidationError("scripted_real_states must be an object")
        self._real_states = {}
        for dev_key, state in real_raw.items():
            try:
                device_id = int(dev_key)
            except (TypeError, ValueError):
                raise CheckerValidationError("bad device key in scripted_real_states: %r" % dev_key)
            if not isinstance(state, dict):
                raise CheckerValidationError("real state of device %d must be an object" % device_id)
            parsed: dict[str, str] = {}
            for proc in ("A", "B", "C"):
                if state.get(proc) not in ("normal", "problem"):
                    raise CheckerValidationError(
                        "real state %s of device %d must be normal|problem" % (proc, device_id))
                parsed[proc] = state[proc]
            if state.get("D") not in ("normal", "problem", "not_created"):
                raise CheckerValidationError("real state D of device %d invalid" % device_id)
            parsed["D"] = state["D"]
            self._real_states[device_id] = parsed
        self._acceptance = raw.get("acceptance") if isinstance(raw.get("acceptance"), dict) else None
        return fixture_id

    def _parse_event_log(self, event_log: Any) -> tuple[list[dict], bool]:
        """Validate the envelope structure, seq monotonicity and per-type
        required fields.  Returns (records, structural_ok)."""
        if isinstance(event_log, dict) and isinstance(event_log.get("records"), list):
            records = event_log["records"]
        elif isinstance(event_log, list):
            records = event_log
        else:
            self._issue("C17", "event_log", "list or {records: [...]}", type(event_log).__name__,
                        "event_log must be a JSON array or an envelope object")
            return [], False
        if not records:
            self._issue("C17", "event_log", "non-empty", "empty",
                        "event_log is empty (explicit FAIL, never a silent PASS)")
            return [], False
        ok = True
        parsed: list[dict] = []
        expected_seq = 1
        prev_time: Optional[Fraction] = None
        for idx, rec in enumerate(records):
            loc = "record[%d]" % idx
            if not isinstance(rec, dict):
                self._issue("C17", loc, "object", type(rec).__name__,
                            "log record must be an object")
                ok = False
                continue
            seq = rec.get("seq")
            if not isinstance(seq, int) or seq != expected_seq:
                self._issue("C17", loc, "seq == %d" % expected_seq, seq,
                            "seq must be a strictly increasing integer starting at 1")
                ok = False
            expected_seq += 1
            event_type = rec.get("event_type")
            if event_type not in EVENT_TYPES:
                self._issue("C17", loc, "one of %s" % sorted(EVENT_TYPES), event_type,
                            "unknown event_type")
                ok = False
            try:
                t = parse_hours(rec.get("event_time"), "%s.event_time" % loc)
                hours_to_ticks(t, "%s.event_time" % loc)
            except CheckerValidationError as exc:
                self._issue("C17", loc, "exact rational string", rec.get("event_time"),
                            "invalid canonical time: %s" % exc)
                ok = False
                t = None
            except NonIntegerTickError as exc:
                self._issue("C18", loc, "integer-multiple-of-1/6h", rec.get("event_time"),
                            "time not on the 10-min tick grid: %s" % exc)
                ok = False
                t = None
            if t is not None:
                if prev_time is not None and t < prev_time:
                    self._issue("C18", loc, ">= %s" % frac_to_str(prev_time), frac_to_str(t),
                                "event_time goes backwards (time must be monotonic)")
                    ok = False
                prev_time = t
            # float time fields anywhere in the record are forbidden
            for tf in TIME_FIELDS:
                if tf in rec and isinstance(rec[tf], float):
                    self._issue("C17", "%s.%s" % (loc, tf), "exact rational string",
                                rec[tf], "float is forbidden as a canonical time")
                    ok = False
            for field_name in REQUIRED_FIELDS.get(event_type, ()):
                if rec.get(field_name) is None:
                    self._issue("C17", "%s.%s" % (loc, event_type),
                                "present", None,
                                "missing required field %s for event_type %s" % (field_name, event_type))
                    ok = False
            parsed.append(rec)
        sim_ends = [r for r in parsed if r.get("event_type") == "SIMULATION_END"]
        if len(sim_ends) != 1:
            self._issue("C17", "event_log", "exactly one SIMULATION_END", len(sim_ends),
                        "SIMULATION_END must appear exactly once (incomplete log is an explicit FAIL)")
            ok = False
        else:
            last = parsed[-1]
            if last.get("event_type") != "SIMULATION_END":
                self._issue("C18", "event_log", "SIMULATION_END as the last record",
                            last.get("event_type"), "SIMULATION_END must be the final record")
                ok = False
        return parsed, ok

    # ------------------------------------------------------------------
    # helpers
    # ------------------------------------------------------------------

    def _issue(self, check_id: str, location: str, expected: Any, actual: Any,
               message: str) -> None:
        self._issues.append(CheckIssue(check_id, location, expected, actual, message))

    def _task_key(self, rec: dict) -> tuple:
        return (rec.get("device_id"), rec.get("process"), rec.get("effective_attempt_no"))

    def _shift_interval(self, index: int) -> Optional[tuple[Fraction, Fraction, int]]:
        """(start, end, squad) of shift `index` per the frozen calendar, or None."""
        scenario = self._cfg["scenario"]
        length = self._cfg["shift_length_h"]
        if scenario == "q3_two_shift":
            day = index // self._cfg["shifts_per_day"]
            slot = index % self._cfg["shifts_per_day"]
            start = Fraction(day) * Fraction(24) + Fraction(slot) * length
            squad = 1 if index % 2 == 0 else 2
            return (start, start + length, squad)
        if scenario == "q2_single_shift":
            start = Fraction(index) * Fraction(24)
            return (start, start + length, 1)
        if index == 0:
            return (Fraction(0), length, 1)
        return None

    def _shift_at(self, t: Fraction) -> Optional[tuple[Fraction, Fraction, int]]:
        index = 0
        while True:
            iv = self._shift_interval(index)
            if iv is None:
                return None
            start, end, squad = iv
            if start <= t < end:
                return iv
            if t < start:
                return None
            index += 1

    # ------------------------------------------------------------------
    # replay views
    # ------------------------------------------------------------------

    def _build_views(self) -> None:
        self._records_by_type = {}
        for rec in self._log:
            self._records_by_type.setdefault(rec.get("event_type"), []).append(rec)
        # tasks
        tasks: dict[tuple, dict[str, Any]] = {}
        for rec in self._log:
            et = rec.get("event_type")
            if et not in ("TASK_RELEASE", "ACTIVITY_START", "ACTIVITY_COMPLETE",
                          "TASK_CANCEL", "OBSERVATION_MATERIALIZED"):
                continue
            key = self._task_key(rec)
            if None in key:
                continue
            view = tasks.setdefault(key, {
                "release_time": None, "release_seq": None, "release_event_time": None,
                "starts": [], "completes": [], "cancels": [], "observations": [],
            })
            if et == "TASK_RELEASE":
                view["release_time"] = parse_hours(rec.get("release_time"), "TASK_RELEASE.release_time")
                view["release_event_time"] = parse_hours(rec.get("event_time"), "TASK_RELEASE.event_time")
                view["release_seq"] = rec.get("seq")
            elif et == "ACTIVITY_START":
                view["starts"].append(rec)
            elif et == "ACTIVITY_COMPLETE":
                view["completes"].append(rec)
            elif et == "TASK_CANCEL":
                view["cancels"].append(rec)
            elif et == "OBSERVATION_MATERIALIZED":
                view["observations"].append(rec)
        self._tasks = tasks
        # devices
        devices: dict[int, dict[str, Any]] = {}
        for rec in self._log:
            et = rec.get("event_type")
            device_id = rec.get("device_id")
            if device_id is None or not isinstance(device_id, int):
                continue
            dev = devices.setdefault(device_id, {
                "terminal_state": None, "terminal_time": None, "terminal_reason": None,
                "d_created": None, "d_state": "not_created", "exit_seq": None,
                "bay_id": None, "entry_time": None,
            })
            if et == "DEVICE_TERMINAL":
                dev["terminal_state"] = rec.get("terminal_state")
                dev["terminal_time"] = parse_hours(rec.get("event_time"), "DEVICE_TERMINAL.event_time")
                dev["terminal_reason"] = rec.get("terminal_reason")
            elif et == "DEVICE_EXIT":
                dev["exit_seq"] = rec.get("seq")
            elif et == "D_CREATED":
                dev["d_created"] = parse_hours(rec.get("event_time"), "D_CREATED.event_time")
                dev["d_state"] = rec.get("d_state")
            elif et == "ACTIVITY_START":
                if dev["bay_id"] is None:
                    dev["bay_id"] = rec.get("bay_id")
        self._devices = devices
        # shifts (from SHIFT_CHANGE records, in seq order)
        self._shifts = []
        for rec in self._log:
            if rec.get("event_type") != "SHIFT_CHANGE":
                continue
            self._shifts.append({
                "seq": rec.get("seq"),
                "time": parse_hours(rec.get("event_time"), "SHIFT_CHANGE.event_time"),
                "shift_index": rec.get("shift_index"),
                "shift_start": parse_hours(rec.get("shift_start"), "SHIFT_CHANGE.shift_start"),
                "shift_end": parse_hours(rec.get("shift_end"), "SHIFT_CHANGE.shift_end"),
                "on_duty_squad": rec.get("on_duty_squad"),
            })
        # turnovers
        self._turnovers = []
        for rec in self._log:
            et = rec.get("event_type")
            if et in ("TURNOVER_OUT_START", "TURNOVER_OUT_COMPLETE",
                      "TURNOVER_IN_START", "TURNOVER_IN_COMPLETE"):
                self._turnovers.append({
                    "seq": rec.get("seq"),
                    "event_type": et,
                    "time": parse_hours(rec.get("event_time"), "%s.event_time" % et),
                    "bay_id": rec.get("bay_id"),
                    "device_id": rec.get("device_id"),
                })
        self._turnovers.sort(key=lambda x: (x["time"], x["seq"]))
        # T
        ends = [r for r in self._log if r.get("event_type") == "SIMULATION_END"]
        if ends:
            self._T = parse_hours(ends[-1]["event_time"], "SIMULATION_END.event_time")

    # ------------------------------------------------------------------
    # checks
    # ------------------------------------------------------------------

    def _check_parameters_cross(self) -> None:
        """Cross-check config vs shared parameters.csv (independent source)."""
        p = self._parameters
        if not p:
            return
        expect = {
            "test_duration_A": self._cfg["durations"]["A"],
            "test_duration_B": self._cfg["durations"]["B"],
            "test_duration_C": self._cfg["durations"]["C"],
            "test_duration_E": self._cfg["durations"]["E"],
            "transport_out": self._cfg["transport_out_h"],
            "transport_in": self._cfg["transport_in_h"],
        }
        for code_name, value in expect.items():
            if code_name in p:
                try:
                    para = parse_hours(p[code_name], "parameters.%s" % code_name)
                except CheckerValidationError:
                    continue  # parameters value not parseable; not a config failure
                if para != value:
                    self._issue("C09", "config_vs_parameters.%s" % code_name,
                                frac_to_str(value), frac_to_str(para),
                                "config value disagrees with shared parameters.csv")
        if p.get("key_schema") not in (None, "key_schema_v1"):
            self._issue("C09", "config_vs_parameters.key_schema",
                        "key_schema_v1", p.get("key_schema"),
                        "key_schema_version disagrees with parameters.csv P061")
        if p.get("capacity_A") not in (None, "1") or p.get("capacity_B") not in (None, "1") \
                or p.get("capacity_C") not in (None, "1") or p.get("capacity_E") not in (None, "1"):
            self._issue("C09", "resource_capacity", "1 (P002-P005)", p,
                        "resource capacities must be 1 per the shared parameters")

    def _check_shift_calendar(self) -> None:
        """SHIFT_CHANGE events must match the frozen calendar exactly."""
        if not self._structural_ok:
            return
        if not self._shifts:
            self._issue("C12", "shift_calendar", ">= 1 SHIFT_CHANGE at t=0", 0,
                        "no SHIFT_CHANGE record in the event log")
            return
        horizon = self._T if self._T is not None else Fraction(0)
        expected: dict[Fraction, tuple] = {}
        index = 0
        while True:
            iv = self._shift_interval(index)
            if iv is None:
                break
            start, end, squad = iv
            if start > horizon:
                break
            expected[start] = (index, start, end, squad)
            index += 1
        seen_times: set[Fraction] = set()
        for shift in self._shifts:
            t = shift["time"]
            seen_times.add(t)
            if t not in expected:
                self._issue("C12", "SHIFT_CHANGE@%s" % frac_to_str(t),
                            "one of %s" % sorted(frac_to_str(k) for k in expected),
                            frac_to_str(t), "SHIFT_CHANGE at a non-boundary time")
                continue
            exp_index, exp_start, exp_end, exp_squad = expected[t]
            if shift["shift_index"] != exp_index:
                self._issue("C12", "SHIFT_CHANGE@%s.shift_index" % frac_to_str(t),
                            exp_index, shift["shift_index"], "shift_index mismatch")
            if shift["shift_start"] != exp_start or shift["shift_end"] != exp_end:
                self._issue("C12", "SHIFT_CHANGE@%s.interval" % frac_to_str(t),
                            "%s..%s" % (frac_to_str(exp_start), frac_to_str(exp_end)),
                            "%s..%s" % (fmt_opt(shift["shift_start"]), fmt_opt(shift["shift_end"])),
                            "shift interval mismatch (half-open [start, end))")
            if shift["on_duty_squad"] != exp_squad:
                self._issue("C12", "SHIFT_CHANGE@%s.on_duty_squad" % frac_to_str(t),
                            exp_squad, shift["on_duty_squad"], "on-duty squad mismatch")
        for t in expected:
            if t not in seen_times:
                self._issue("C12", "shift_boundary@%s" % frac_to_str(t),
                            "SHIFT_CHANGE present", "missing",
                            "missing SHIFT_CHANGE at the frozen shift boundary")

    def _check_task_lifecycle(self) -> None:
        """Per-task release/start/end, durations, outcomes, cancel reasons and
        shift feasibility (SEM-18/19/20)."""
        if not self._structural_ok:
            return
        durations = self._cfg["durations"]
        for key in sorted(self._tasks, key=lambda k: (k[0], PROCESS_ORDER[k[1]], k[2])):
            view = self._tasks[key]
            device_id, process, attempt = key
            loc = "task(%d,%s,%d)" % key
            release = view["release_time"]
            release_evt = view["release_event_time"]
            starts = view["starts"]
            completes = view["completes"]
            cancels = view["cancels"]
            observations = view["observations"]
            if release is None:
                self._issue("C09", loc, "TASK_RELEASE present", "missing",
                            "task activity without a TASK_RELEASE record")
                continue
            if release_evt is not None and release != release_evt:
                self._issue("C11", "%s.release_time" % loc,
                            frac_to_str(release_evt), frac_to_str(release),
                            "release_time must equal the TASK_RELEASE event time "
                            "(task is released exactly at its logical release moment)")
            if len(starts) > 1:
                self._issue("C09", loc, "<= 1 ACTIVITY_START", len(starts),
                            "task started more than once")
            if len(completes) > 1:
                self._issue("C09", loc, "<= 1 ACTIVITY_COMPLETE", len(completes),
                            "task completed more than once")
            if len(cancels) > 1:
                self._issue("C10", loc, "<= 1 TASK_CANCEL", len(cancels),
                            "task cancelled more than once")
            if len(observations) > 1:
                self._issue("C09", loc, "<= 1 OBSERVATION_MATERIALIZED", len(observations),
                            "more than one observation for one task")
            completed = len(completes) == 1
            cancelled = len(cancels) == 1
            if completed and cancelled:
                self._issue("C09", loc, "exactly one terminal state", "complete+cancel",
                            "task is both completed and cancelled")
            if not completed and not cancelled:
                self._issue("C18", loc, "COMPLETED or CANCELLED", "RELEASED_UNFINISHED",
                            "released task never reached a terminal state at SIMULATION_END")
                continue
            start = None
            if starts:
                start = parse_hours(starts[0].get("event_time"), "%s.start" % loc)
                if parse_hours(starts[0].get("attempt_start_time"), "%s.attempt_start_time" % loc) != start:
                    self._issue("C09", "%s.attempt_start_time" % loc,
                                frac_to_str(start), starts[0].get("attempt_start_time"),
                                "ACTIVITY_START event_time != attempt_start_time")
                if start < release:
                    self._issue("C11", "%s.start" % loc, ">= %s" % frac_to_str(release),
                                frac_to_str(start), "task started before its release_time")
                # FCFS key reconstruction (release_time frozen, squad excluded)
                key_tuple = (release, device_id, PROCESS_ORDER[process], attempt)
                if len(key_tuple) != 4:
                    self._issue("C11", loc, "4-tuple FCFS key", key_tuple,
                                "FCFS key must be (release_time, device_id, process_order, attempt)")
                self._recomputed.setdefault("fcfs_keys", {})[
                    "D%03d_%s_%d" % key] = [frac_to_str(k) if isinstance(k, Fraction) else k
                                             for k in key_tuple]
            if cancelled:
                cancel = cancels[0]
                reason = cancel.get("cancel_reason")
                if reason not in CANCEL_REASONS:
                    self._issue("C10", "%s.cancel_reason" % loc, "DEVICE_EXIT|SHIFT_INTERRUPT",
                                reason, "invalid cancel reason")
                if cancel.get("outcome") != "NONE":
                    self._issue("C10", "%s.outcome" % loc, "NONE", cancel.get("outcome"),
                                "cancelled fragment must have outcome NONE (no observation)")
                if observations:
                    self._issue("C10", "%s.observation" % loc, "none", len(observations),
                                "cancelled fragment must have no OBSERVATION_MATERIALIZED")
                elapsed = parse_hours(cancel.get("elapsed_hours"), "%s.elapsed" % loc)
                cancel_time = parse_hours(cancel.get("event_time"), "%s.cancel_time" % loc)
                if elapsed == 0:
                    if start is not None:
                        self._issue("C10", "%s.cancel_elapsed" % loc,
                                    "0 (never started, READY cancelled)", elapsed,
                                    "cancelled fragment with elapsed=0 must have no ACTIVITY_START")
                else:
                    if start is None:
                        self._issue("C10", "%s.cancel_elapsed" % loc,
                                    "> 0 requires a started fragment", elapsed,
                                    "cancelled fragment with elapsed>0 has no ACTIVITY_START")
                    else:
                        if cancel_time != start + elapsed:
                            self._issue("C10", "%s.cancel_time" % loc,
                                        frac_to_str(start + elapsed), frac_to_str(cancel_time),
                                        "cancel_time must equal start + elapsed_hours")
                        if cancel.get("attempt_end_time") is not None and \
                                parse_hours(cancel.get("attempt_end_time"), "%s.attempt_end_time" % loc) != cancel_time:
                            self._issue("C09", "%s.attempt_end_time" % loc,
                                        frac_to_str(cancel_time), cancel.get("attempt_end_time"),
                                        "TASK_CANCEL event_time != attempt_end_time")
            if completed:
                complete = completes[0]
                end = parse_hours(complete.get("event_time"), "%s.complete" % loc)
                if start is None:
                    self._issue("C09", loc, "ACTIVITY_START present", "missing",
                                "completed task has no ACTIVITY_START")
                else:
                    expected_end = start + durations[process]
                    if end != expected_end:
                        self._issue("C09", "%s.finish" % loc,
                                    frac_to_str(expected_end), frac_to_str(end),
                                    "finish must equal start + frozen duration")
                    if complete.get("attempt_start_time") is not None and \
                            parse_hours(complete.get("attempt_start_time"), "%s.attempt_start_time" % loc) != start:
                        self._issue("C09", "%s.attempt_start_time" % loc,
                                    frac_to_str(start), complete.get("attempt_start_time"),
                                    "ACTIVITY_COMPLETE attempt_start_time != ACTIVITY_START")
                    if complete.get("attempt_end_time") is not None and \
                            parse_hours(complete.get("attempt_end_time"), "%s.attempt_end_time" % loc) != end:
                        self._issue("C09", "%s.attempt_end_time" % loc,
                                    frac_to_str(end), complete.get("attempt_end_time"),
                                    "ACTIVITY_COMPLETE event_time != attempt_end_time")
                elapsed = parse_hours(complete.get("elapsed_hours"), "%s.elapsed" % loc)
                if elapsed != durations[process]:
                    self._issue("C09", "%s.elapsed_hours" % loc,
                                frac_to_str(durations[process]), frac_to_str(elapsed),
                                "completed fragment elapsed_hours must equal the frozen duration")
                if cancels:
                    self._issue("C09", loc, "no TASK_CANCEL", len(cancels),
                                "completed task must not be cancelled")
                if not observations:
                    self._issue("C09", "%s.outcome" % loc,
                                "OBSERVATION_MATERIALIZED present", "missing",
                                "completed effective test has no observation")
                else:
                    obs = observations[0]
                    obs_time = parse_hours(obs.get("event_time"), "%s.obs_time" % loc)
                    if obs_time != end:
                        self._issue("C09", "%s.observation_time" % loc,
                                    frac_to_str(end), frac_to_str(obs_time),
                                    "observation must be materialized at the completion time")
                    outcome = obs.get("outcome")
                    if outcome not in ("PASS", "ABNORMAL"):
                        self._issue("C09", "%s.outcome" % loc, "PASS|ABNORMAL", outcome,
                                    "observation outcome invalid")
                    scripted = self._scripted_outcomes.get(key)
                    if scripted is None:
                        self._issue("C09", "%s.outcome" % loc,
                                    "scripted outcome present", "MISSING_SCRIPTED_OUTCOME",
                                    "MISSING_SCRIPTED_OUTCOME: completed effective test "
                                    "(device=%d, process=%s, attempt=%d) has no scripted outcome"
                                    % key)
                    elif outcome != scripted:
                        self._issue("C09", "%s.outcome" % loc, scripted, outcome,
                                    "observation disagrees with the scripted outcome")
                if self._T is not None and end > self._T:
                    self._issue("C12", "%s.finish" % loc, "<= T (%s)" % frac_to_str(self._T),
                                frac_to_str(end), "activity ends after T")
            # shift feasibility (SEM-18/19/20): a started fragment must fit its shift
            if start is not None:
                shift = self._shift_at(start)
                if shift is None:
                    self._issue("C12", "%s.start" % loc, "within an active shift", frac_to_str(start),
                                "activity started outside any shift (shift gap)")
                else:
                    shift_start, shift_end, _squad = shift
                    end = None
                    if completed:
                        end = parse_hours(completes[0].get("event_time"), "%s.complete" % loc)
                    elif cancelled and parse_hours(cancels[0].get("elapsed_hours"), "elapsed") != 0:
                        end = parse_hours(cancels[0].get("event_time"), "%s.cancel_time" % loc)
                    if end is not None and end > shift_end:
                        self._issue("C12", "%s.shift_feasibility" % loc,
                                    "end <= shift_end (%s)" % frac_to_str(shift_end),
                                    frac_to_str(end),
                                    "activity crosses the shift boundary (SEM-18/20)")

    def _check_release_time(self) -> None:
        """release_time is frozen: every record carrying release_time for a task
        must carry the identical value (K9: cross-shift invariance)."""
        if not self._structural_ok:
            return
        by_task: dict[tuple, list[Fraction]] = {}
        for rec in self._log:
            if "release_time" not in rec:
                continue
            key = self._task_key(rec)
            if None in key:
                continue
            by_task.setdefault(key, []).append(
                parse_hours(rec.get("release_time"), "release_time"))
        for key in sorted(by_task, key=lambda k: (k[0], PROCESS_ORDER[k[1]], k[2])):
            values = by_task[key]
            first = values[0]
            for value in values[1:]:
                if value != first:
                    self._issue("C11", "task(%d,%s,%d).release_time" % key,
                                frac_to_str(first), frac_to_str(value),
                                "release_time rewritten across records "
                                "(must stay frozen, incl. across shift changes)")

    def _check_attempts(self) -> None:
        """effective_attempt_no: 1 < 2; only a completed first ABNORMAL
        advances the attempt; cancelled fragments never advance (SEM-10/12)."""
        if not self._structural_ok:
            return
        per_process: dict[tuple, list[dict]] = {}
        for rec in self._log:
            if rec.get("event_type") == "OBSERVATION_MATERIALIZED":
                key = self._task_key(rec)
                if None in key:
                    continue
                per_process.setdefault((key[0], key[1]), []).append(rec)
        for (device_id, process), obs_list in sorted(per_process.items()):
            loc = "device(%d).%s" % (device_id, process)
            obs_list.sort(key=lambda r: r["seq"])
            attempts = [r.get("effective_attempt_no") for r in obs_list]
            if any(a not in (1, 2) for a in attempts):
                self._issue("C10", loc, "{1, 2}", attempts,
                            "effective_attempt_no must be 1 or 2")
            if attempts != sorted(attempts):
                self._issue("C10", loc, "non-decreasing (1 < 2)", attempts,
                            "attempt numbers must be monotonic in seq order")
            abnormal_seen = 0
            for rec in obs_list:
                a = rec.get("effective_attempt_no")
                if a == 2 and abnormal_seen < 1:
                    self._issue("C10", "%s.attempt_2" % loc,
                                "a completed first ABNORMAL before it", a,
                                "attempt 2 without a completed first ABNORMAL")
                if rec.get("outcome") == "ABNORMAL":
                    abnormal_seen += 1
        # cancelled fragments keep the current logical attempt number
        for key in sorted(self._tasks, key=lambda k: (k[0], PROCESS_ORDER[k[1]], k[2])):
            view = self._tasks[key]
            if not view["cancels"]:
                continue
            device_id, process, attempt = key
            prior = [r for r in self._log
                     if r.get("event_type") == "OBSERVATION_MATERIALIZED"
                     and r.get("device_id") == device_id and r.get("process") == process
                     and r.get("effective_attempt_no") == 1 and r.get("outcome") == "ABNORMAL"]
            expected_attempt = 1 + len(prior)
            if attempt != expected_attempt:
                self._issue("C10", "task(%d,%s,%d).cancel_attempt" % key,
                            expected_attempt, attempt,
                            "cancelled fragment's attempt number must equal the current "
                            "logical attempt (cancellation never advances the attempt)")

    def _check_devices(self) -> None:
        """Terminal state, terminal time, D materialization timing, S/PL/PW."""
        if not self._structural_ok:
            return
        batch_size = self._cfg["batch_size"]
        for device_id in range(1, batch_size + 1):
            loc = "device(%d)" % device_id
            dev = self._devices.get(device_id)
            if dev is None or dev["terminal_state"] is None:
                self._issue("C10", loc, "DEVICE_TERMINAL present", "missing",
                            "device has no terminal state at SIMULATION_END")
                continue
            terminal = dev["terminal_state"]
            term_time = dev["terminal_time"]
            if terminal == "PASSED":
                if dev["terminal_reason"] is not None:
                    self._issue("C10", "%s.terminal_reason" % loc, None,
                                dev["terminal_reason"],
                                "PASSED terminal_reason must be null")
                e_obs = [r for r in self._log
                         if r.get("event_type") == "OBSERVATION_MATERIALIZED"
                         and r.get("device_id") == device_id and r.get("process") == "E"
                         and r.get("outcome") == "PASS"]
                if not e_obs:
                    self._issue("C09", loc, "E PASS observation at terminal time", "missing",
                                "PASSED device must have a completed E PASS")
                else:
                    if parse_hours(e_obs[-1].get("event_time"), "E.obs_time") != term_time:
                        self._issue("C09", "%s.terminal_time" % loc,
                                    frac_to_str(term_time), e_obs[-1].get("event_time"),
                                    "PASSED terminal time must equal the E PASS completion time")
            elif terminal == "EXITED":
                if dev["terminal_reason"] != TERMINAL_REASON_SECOND_ABNORMAL:
                    self._issue("C10", "%s.terminal_reason" % loc,
                                TERMINAL_REASON_SECOND_ABNORMAL, dev["terminal_reason"],
                                "EXITED terminal_reason must be process_second_abnormal")
                if dev["exit_seq"] is None:
                    self._issue("C10", loc, "DEVICE_EXIT present", "missing",
                                "EXITED device has no DEVICE_EXIT record")
                else:
                    term_rec = [r for r in self._log
                                if r.get("event_type") == "DEVICE_TERMINAL"
                                and r.get("device_id") == device_id]
                    if term_rec and dev["exit_seq"] >= term_rec[0].get("seq"):
                        self._issue("C10", "%s.order" % loc, "DEVICE_EXIT.seq < DEVICE_TERMINAL.seq",
                                    (dev["exit_seq"], term_rec[0].get("seq")),
                                    "DEVICE_EXIT must precede DEVICE_TERMINAL")
            else:
                self._issue("C10", loc, "PASSED|EXITED", terminal, "invalid terminal_state")
        # T == last terminal judgment == SIMULATION_END
        terminals = [dev["terminal_time"] for dev in self._devices.values()
                     if dev["terminal_time"] is not None]
        if terminals:
            max_term = max(terminals)
            if self._T is not None and max_term != self._T:
                self._issue("C12", "T", frac_to_str(self._T), frac_to_str(max_term),
                            "SIMULATION_END time must equal the last DEVICE_TERMINAL time")
        # D materialization (E2 rules, V1.0.2)
        self._check_d_materialization()
        # S/PL/PW
        self._recompute_quality()

    def _check_d_materialization(self) -> None:
        """E2: D is created exactly once, at the A/B/C all-PASS timestamp, at
        the E initial TASK_RELEASE timestamp (D_CREATED.seq < TASK_RELEASE.seq),
        never at the E ACTIVITY_START, never regenerated by an E retest;
        early-exit devices keep d_state=not_created."""
        for device_id in range(1, self._cfg["batch_size"] + 1):
            loc = "device(%d).D" % device_id
            d_recs = [r for r in self._log
                      if r.get("event_type") == "D_CREATED"
                      and r.get("device_id") == device_id]
            e_rel = [r for r in self._log
                     if r.get("event_type") == "TASK_RELEASE"
                     and r.get("device_id") == device_id and r.get("process") == "E"
                     and r.get("effective_attempt_no") == 1]
            e_rel2 = [r for r in self._log
                      if r.get("event_type") == "TASK_RELEASE"
                      and r.get("device_id") == device_id and r.get("process") == "E"
                      and r.get("effective_attempt_no") == 2]
            del e_rel2  # E retests must never regenerate D: enforced by the
            # "exactly 1 D_CREATED" + timing checks below (F6/F11 cover it).
            if e_rel:
                if len(d_recs) != 1:
                    self._issue("C09", loc, "exactly 1 D_CREATED", len(d_recs),
                                "E-eligible device must materialize D exactly once "
                                "(an E retest must never regenerate D)")
                if d_recs:
                    d = d_recs[0]
                    d_time = parse_hours(d.get("event_time"), "D_CREATED.event_time")
                    e_time = parse_hours(e_rel[0].get("event_time"), "E TASK_RELEASE.event_time")
                    if d_time != e_time:
                        self._issue("C09", "%s.timing" % loc,
                                    frac_to_str(e_time), frac_to_str(d_time),
                                    "D_CREATED must share the E initial TASK_RELEASE timestamp")
                    if d.get("seq") >= e_rel[0].get("seq"):
                        self._issue("C09", "%s.seq_order" % loc,
                                    "D_CREATED.seq < TASK_RELEASE(E).seq",
                                    (d.get("seq"), e_rel[0].get("seq")),
                                    "E2 (D) must precede F (E release) at the same timestamp")
                    scripted_d = self._real_states.get(device_id, {}).get("D", "not_created")
                    if d.get("d_state") != scripted_d:
                        self._issue("C09", "%s.d_state" % loc, scripted_d, d.get("d_state"),
                                    "D_CREATED d_state disagrees with the scripted real state")
                    if scripted_d == "not_created":
                        self._issue("C09", "%s.d_state" % loc,
                                    "normal|problem", scripted_d,
                                    "fixture inconsistency: E-eligible device has scripted D "
                                    "'not_created'")
            else:
                if d_recs:
                    self._issue("C09", loc, "no D_CREATED", len(d_recs),
                                "device that never became E-eligible (early exit) must not "
                                "generate D (no anti-factual D)")
            # E ACTIVITY_START must never create D: no D_CREATED at an E start
            # timestamp unless that timestamp also carries the E release.
            e_starts = [r for r in self._log
                        if r.get("event_type") == "ACTIVITY_START"
                        and r.get("device_id") == device_id and r.get("process") == "E"]
            for est in e_starts:
                t = parse_hours(est.get("event_time"), "E.start")
                for d in d_recs:
                    if parse_hours(d.get("event_time"), "D_CREATED.event_time") == t \
                            and (not e_rel or parse_hours(e_rel[0].get("event_time"), "E.rel") != t):
                        self._issue("C09", "%s.e_start_d" % loc, "no D at E ACTIVITY_START", t,
                                    "D must not be generated at the E ACTIVITY_START timestamp "
                                    "(it is generated at the E release timestamp)")

    def _recompute_quality(self) -> None:
        batch_size = self._cfg["batch_size"]
        passed: list[int] = []
        exited: list[int] = []
        for device_id in range(1, batch_size + 1):
            dev = self._devices.get(device_id, {})
            terminal = dev.get("terminal_state")
            if terminal == "PASSED":
                passed.append(device_id)
            elif terminal == "EXITED":
                exited.append(device_id)

        def generated_problems(device_id: int) -> list[str]:
            problems: list[str] = []
            real = self._real_states.get(device_id, {})
            for proc in ("A", "B", "C"):
                if real.get(proc) == "problem":
                    problems.append(proc)
            d_state = self._devices.get(device_id, {}).get("d_state", "not_created")
            if d_state == "problem":
                problems.append("D")
            return problems

        pl = sum(1 for d in passed if generated_problems(d))
        pw = sum(1 for d in exited if not generated_problems(d))
        self._recomputed["S"] = len(passed)
        self._recomputed["PL"] = pl
        self._recomputed["PW"] = pw

    def _check_turnovers(self) -> None:
        """Turnover event ordering, durations and the 0.5h_overlap folding rule."""
        if not self._structural_ok:
            return
        profile = self._cfg["turnover_profile"]
        out_h = self._cfg["transport_out_h"]
        in_h = self._cfg["transport_in_h"]
        by_bay: dict[int, list[dict]] = {}
        for tv in self._turnovers:
            by_bay.setdefault(tv["bay_id"], []).append(tv)
        last_device = self._cfg["batch_size"]
        for bay_id in sorted(by_bay):
            events = by_bay[bay_id]
            loc = "turnover.bay(%d)" % bay_id
            out_starts = [e for e in events if e["event_type"] == "TURNOVER_OUT_START"]
            out_completes = [e for e in events if e["event_type"] == "TURNOVER_OUT_COMPLETE"]
            in_starts = [e for e in events if e["event_type"] == "TURNOVER_IN_START"]
            in_completes = [e for e in events if e["event_type"] == "TURNOVER_IN_COMPLETE"]
            if not (len(out_starts) == len(out_completes) == len(in_starts) == len(in_completes)):
                self._issue("C12", loc, "equal counts of OUT/IN phases",
                            (len(out_starts), len(out_completes), len(in_starts), len(in_completes)),
                            "unbalanced turnover phases")
                continue
            for i in range(len(out_starts)):
                os_ = out_starts[i]["time"]
                oc = out_completes[i]["time"]
                is_ = in_starts[i]["time"]
                ic = in_completes[i]["time"]
                tloc = "%s[%d]" % (loc, i)
                if os_ >= oc:
                    self._issue("C12", tloc, "OUT_START < OUT_COMPLETE",
                                (frac_to_str(os_), frac_to_str(oc)), "out phase not strictly increasing")
                if oc != is_:
                    self._issue("C12", tloc, "OUT_COMPLETE == IN_START",
                                (frac_to_str(oc), frac_to_str(is_)),
                                "turnover out and in phases must be contiguous")
                if profile == "0.5h_overlap":
                    # zero-duration IN log representation: IN_START == IN_COMPLETE
                    if is_ != ic:
                        self._issue("C12", tloc,
                                    "IN_START == IN_COMPLETE (zero-duration IN log rep.)",
                                    (frac_to_str(is_), frac_to_str(ic)),
                                    "0.5h_overlap must record the IN phases at one timestamp")
                    if oc - os_ != out_h:
                        self._issue("C12", "%s.physical_duration" % tloc,
                                    frac_to_str(out_h), frac_to_str(oc - os_),
                                    "0.5h_overlap physical turnover occupancy must be "
                                    "transport_out_h (no extra IN occupancy)")
                else:
                    if ic <= is_:
                        self._issue("C12", tloc, "IN_START < IN_COMPLETE",
                                    (frac_to_str(is_), frac_to_str(ic)),
                                    "in phase not strictly increasing")
                    if oc - os_ != out_h:
                        self._issue("C12", "%s.out_duration" % tloc,
                                    frac_to_str(out_h), frac_to_str(oc - os_),
                                    "OUT phase duration mismatch (P014)")
                    if ic - is_ != in_h:
                        self._issue("C12", "%s.in_duration" % tloc,
                                    frac_to_str(in_h), frac_to_str(ic - is_),
                                    "IN phase duration mismatch (P015)")
            for out_start in out_starts:
                departed = out_start.get("device_id")
                if departed is not None and departed == last_device:
                    self._issue("C12", "%s.last_device" % loc, "no turnover for the last device",
                                departed, "the last device must not be transported out (SEM-22)")

    def _check_bay_coverage(self) -> None:
        """Bay occupancy: per bay, device residency intervals + physical
        turnover intervals must tile [0, T) without gaps or overlaps; the
        0.5h_overlap IN representation is folded (never double counted)."""
        if not self._structural_ok:
            return
        T = self._T
        if T is None:
            return
        preloaded = list(self._cfg["preloaded_devices"])
        entry: dict[int, tuple[int, Fraction]] = {}
        for idx, device_id in enumerate(preloaded):
            entry[device_id] = (idx + 1, Fraction(0))
        next_device = len(preloaded) + 1
        for tv in sorted(self._turnovers, key=lambda x: (x["seq"],)):
            if tv["event_type"] != "TURNOVER_IN_COMPLETE":
                continue
            if next_device > self._cfg["batch_size"]:
                self._issue("C12", "turnover_in", "device <= batch_size", next_device,
                            "turnover-in without a next device (empty transport-in)")
                continue
            entry[next_device] = (tv["bay_id"], tv["time"])
            next_device += 1
        # device residency end: turnover-out start time, else T (terminal-until-stop)
        residency_end: dict[int, Fraction] = {}
        for device_id in range(1, self._cfg["batch_size"] + 1):
            residency_end[device_id] = T
        for tv in self._turnovers:
            if tv["event_type"] == "TURNOVER_OUT_START" and tv.get("device_id") is not None:
                residency_end[tv["device_id"]] = tv["time"]
        # physical turnover intervals per bay: 1h_literal occupies OUT + IN;
        # 0.5h_overlap occupies a single [out_start, out_complete) (the IN
        # phases are a zero-duration log representation and are FOLDED).
        turnover_physical: dict[int, list[tuple[Fraction, Fraction]]] = {b: [] for b in BAY_IDS}
        profile = self._cfg["turnover_profile"]
        for tv in self._turnovers:
            if tv["event_type"] != "TURNOVER_OUT_START":
                continue
            bay = tv["bay_id"]
            oc = next((e for e in self._turnovers
                       if e["event_type"] == "TURNOVER_OUT_COMPLETE" and e["bay_id"] == bay), None)
            if oc is None:
                continue
            if profile == "0.5h_overlap":
                turnover_physical[bay].append((tv["time"], oc["time"]))
            else:
                is_ = next((e for e in self._turnovers
                            if e["event_type"] == "TURNOVER_IN_START" and e["bay_id"] == bay), None)
                ic = next((e for e in self._turnovers
                           if e["event_type"] == "TURNOVER_IN_COMPLETE" and e["bay_id"] == bay), None)
                turnover_physical[bay].append((tv["time"], oc["time"]))
                if is_ is not None and ic is not None:
                    turnover_physical[bay].append((is_["time"], ic["time"]))
        for bay_id in BAY_IDS:
            bay_devices = sorted(d for d, (b, _t) in entry.items() if b == bay_id)
            if not bay_devices:
                # EMPTY bay (batch_size==1 -> bay2): must have no records at all
                bay_recs = [r for r in self._log if r.get("bay_id") == bay_id]
                if bay_recs:
                    self._issue("C12", "bay(%d)" % bay_id, "no events (EMPTY bay)", len(bay_recs),
                                "EMPTY bay must not carry any event (SEM-21/EMPTY)")
                continue
            intervals: list[tuple[Fraction, Fraction]] = []
            for device_id in bay_devices:
                _b, entry_t = entry[device_id]
                intervals.append((entry_t, residency_end[device_id]))
            for iv in turnover_physical[bay_id]:
                intervals.append(iv)
            intervals.sort(key=lambda iv: (iv[0], iv[1]))
            loc = "bay(%d).coverage" % bay_id
            # gapless tiling of [0, T)
            merged: list[tuple[Fraction, Fraction]] = []
            for start, end in intervals:
                if end <= start:
                    self._issue("C12", loc, "end > start", (frac_to_str(start), frac_to_str(end)),
                                "zero/negative bay interval")
                    continue
                if merged and start < merged[-1][1]:
                    self._issue("C12", loc, "non-overlapping intervals",
                                (frac_to_str(start), frac_to_str(merged[-1][1])),
                                "bay occupancy intervals overlap")
                    continue
                if merged and start != merged[-1][1]:
                    self._issue("C12", loc, "gapless (prev_end == next_start)",
                                (frac_to_str(merged[-1][1]), frac_to_str(start)),
                                "bay occupancy has a gap")
                    continue
                merged.append((start, end))
            if merged:
                if merged[0][0] != Fraction(0):
                    self._issue("C12", loc, "coverage starts at 0", frac_to_str(merged[0][0]),
                                "bay occupancy does not start at t=0")
                if merged[-1][1] != T:
                    self._issue("C12", loc, "coverage ends at T (%s)" % frac_to_str(T),
                                frac_to_str(merged[-1][1]),
                                "bay occupancy does not cover [0, T)")
            # no test activity during a physical turnover interval
            for iv in turnover_physical[bay_id]:
                for rec in self._log:
                    if rec.get("event_type") == "ACTIVITY_START" and rec.get("bay_id") == bay_id:
                        t = parse_hours(rec.get("event_time"), "ACTIVITY_START.event_time")
                        if iv[0] <= t < iv[1]:
                            self._issue("C12", "bay(%d).test_during_turnover" % bay_id,
                                        "no test on bay during turnover",
                                        frac_to_str(t),
                                        "test started on a bay inside a physical turnover interval")
                            break
            self._recomputed.setdefault("bay_coverage", {})[str(bay_id)] = {
                "intervals": [[frac_to_str(s), frac_to_str(e)] for s, e in merged],
                "gapless": True,
            }
        # device bay/entry consistency
        for device_id in range(1, self._cfg["batch_size"] + 1):
            if device_id not in entry:
                continue
            bay_id, entry_t = entry[device_id]
            dev = self._devices.get(device_id, {})
            if dev.get("bay_id") is not None and dev["bay_id"] != bay_id:
                self._issue("C09", "device(%d).bay" % device_id, bay_id, dev["bay_id"],
                            "device bay_id inconsistent across its ACTIVITY_START records")
            initials = [r for r in self._log
                        if r.get("event_type") == "TASK_RELEASE"
                        and r.get("device_id") == device_id
                        and r.get("process") in ("A", "B", "C")
                        and r.get("effective_attempt_no") == 1]
            for rec in initials:
                rel_t = parse_hours(rec.get("release_time"), "initial release")
                if rel_t != entry_t:
                    self._issue("C09", "device(%d).entry_time" % device_id,
                                frac_to_str(entry_t), frac_to_str(rel_t),
                                "initial A/B/C release_time must equal the device entry time")
                    break

    def _check_resource_occupancy(self) -> None:
        """Per resource: capacity-1 BUSY intervals from the log must be pairwise
        disjoint, within [0, T) and within a shift; IDLE elsewhere."""
        if not self._structural_ok:
            return
        T = self._T
        for resource in PROCESSES:
            busy: list[tuple[Fraction, Fraction, tuple]] = []
            for rec in self._log:
                if rec.get("event_type") == "ACTIVITY_START" and rec.get("resource_id") == resource:
                    key = self._task_key(rec)
                    start = parse_hours(rec.get("event_time"), "ACTIVITY_START.event_time")
                    end = None
                    for r2 in self._log:
                        if r2.get("event_type") in ("ACTIVITY_COMPLETE", "TASK_CANCEL") \
                                and self._task_key(r2) == key:
                            end = parse_hours(r2.get("event_time"), "terminal.event_time")
                            break
                    if end is None:
                        self._issue("C18", "resource(%s).dangling" % resource,
                                    "ACTIVITY_COMPLETE or TASK_CANCEL", "missing",
                                    "started activity %s has no terminal record (dangling RUNNING)"
                                    % (key,))
                        continue
                    busy.append((start, end, key))
            busy.sort(key=lambda iv: (iv[0], iv[1]))
            loc = "resource(%s).busy" % resource
            prev_end: Optional[Fraction] = None
            total = Fraction(0)
            for start, end, key in busy:
                if end <= start:
                    self._issue("C09", loc, "end > start",
                                (frac_to_str(start), frac_to_str(end)),
                                "non-positive activity interval")
                    continue
                if T is not None and end > T:
                    self._issue("C12", loc, "<= T", frac_to_str(end),
                                "activity ends after T")
                if prev_end is not None and start < prev_end:
                    self._issue("C09", loc, "disjoint intervals (capacity 1)",
                                (frac_to_str(start), frac_to_str(prev_end)),
                                "two activities overlap on resource %s" % resource)
                if prev_end is not None and start == prev_end:
                    pass  # back-to-back is fine (half-open)
                total += end - start
                shift = self._shift_at(start)
                if shift is None:
                    self._issue("C12", loc, "within an active shift", frac_to_str(start),
                                "activity started outside any shift")
                elif end > shift[1]:
                    self._issue("C12", loc, "end <= shift_end (%s)" % frac_to_str(shift[1]),
                                frac_to_str(end),
                                "activity crosses the shift boundary (SEM-18/20)")
                prev_end = max(prev_end, end) if prev_end is not None else end
            self._recomputed.setdefault("resource_busy", {})[resource] = {
                "intervals": [[frac_to_str(s), frac_to_str(e)] for s, e, _k in busy],
                "total_h": frac_to_str(total),
            }

    def _check_same_timestamp_order(self) -> None:
        """Frozen A..I closure order at each timestamp (settle -> observe ->
        classify -> exit -> cancel -> E2 D -> shift -> release -> dispatch)."""
        if not self._structural_ok:
            return
        by_time: dict[Fraction, list[dict]] = {}
        for rec in self._log:
            t = parse_hours(rec.get("event_time"), "event_time")
            by_time.setdefault(t, []).append(rec)
        for t in sorted(by_time):
            group = by_time[t]
            group.sort(key=lambda r: r["seq"])
            loc = "order@%s" % frac_to_str(t)

            def first_last(event_type: str) -> Optional[tuple[int, int]]:
                seqs = [r["seq"] for r in group if r.get("event_type") == event_type]
                if not seqs:
                    return None
                return (min(seqs), max(seqs))

            wake = first_last("WAKE_UP")
            if wake is not None:
                if group[0].get("event_type") != "WAKE_UP":
                    self._issue("C18", loc, "WAKE_UP first at its timestamp", group[0].get("event_type"),
                                "WAKE_UP must be the first record of its timestamp")
                if self._shift_at(t) is None:
                    self._issue("C18", loc, "shift boundary", frac_to_str(t),
                                "WAKE_UP only at a shift boundary")

            def check_pair(a_type: str, b_type: str, note: str) -> None:
                a = first_last(a_type)
                b = first_last(b_type)
                if a is not None and b is not None and a[1] >= b[0]:
                    self._issue("C18", loc, "%s.seq < %s.seq (%s)" % (a_type, b_type, note),
                                (a[1], b[0]),
                                "%s must strictly precede %s at the same timestamp" % (a_type, b_type))

            check_pair("ACTIVITY_COMPLETE", "OBSERVATION_MATERIALIZED", "A settle -> B observe")
            check_pair("OBSERVATION_MATERIALIZED", "DEVICE_EXIT", "B observe -> D exit")
            check_pair("DEVICE_TERMINAL", "TASK_CANCEL", "D terminal -> E cancel")
            check_pair("TASK_CANCEL", "D_CREATED", "E cancel -> E2 D")
            check_pair("D_CREATED", "SHIFT_CHANGE", "E2 D -> SHIFT_CHANGE")
            check_pair("SHIFT_CHANGE", "TASK_RELEASE", "SHIFT_CHANGE -> F release")
            check_pair("TASK_RELEASE", "ACTIVITY_START", "F release -> H dispatch")
            check_pair("TASK_RELEASE", "TURNOVER_OUT_START", "F release -> G/H turnover start")
            check_pair("DEVICE_TERMINAL", "TURNOVER_OUT_START", "D terminal -> G/H turnover start")
            check_pair("DEVICE_EXIT", "DEVICE_TERMINAL", "D exit -> D terminal")
        # per-task: release before start (global)
        for key in sorted(self._tasks, key=lambda k: (k[0], PROCESS_ORDER[k[1]], k[2])):
            view = self._tasks[key]
            if view["release_seq"] is not None and view["starts"]:
                start_seq = view["starts"][0].get("seq")
                if view["release_seq"] >= start_seq:
                    self._issue("C18", "task(%d,%s,%d).order" % key,
                                "TASK_RELEASE.seq < ACTIVITY_START.seq",
                                (view["release_seq"], start_seq),
                                "task started before its release record")

    def _check_ledger_yxb(self) -> None:
        """YXB / age ledger seam: per-process elapsed = sum of elapsed_hours
        over completed AND cancelled fragments; YXB_j = elapsed_j / (shift_count
        * shift_length)."""
        if not self._structural_ok:
            return
        elapsed: dict[str, Fraction] = {p: Fraction(0) for p in PROCESSES}
        for rec in self._log:
            if rec.get("event_type") in ("ACTIVITY_COMPLETE", "TASK_CANCEL") \
                    and rec.get("process") in PROCESSES:
                elapsed[rec["process"]] += parse_hours(
                    rec.get("elapsed_hours"), "elapsed_hours")
        self._recomputed["elapsed_by_process"] = {p: frac_to_str(elapsed[p]) for p in PROCESSES}
        # shift_count = number of shifts with start < T
        T = self._T
        shift_count = 0
        if T is not None:
            index = 0
            while True:
                iv = self._shift_interval(index)
                if iv is None:
                    break
                start, _end, _squad = iv
                if start < T:
                    shift_count += 1
                    index += 1
                    continue
                break
        denominator = Fraction(shift_count) * self._cfg["shift_length_h"]
        self._recomputed["shift_count"] = shift_count
        self._recomputed["yxb_denominator_h"] = frac_to_str(denominator)
        yxb: dict[str, str] = {}
        for proc in PROCESSES:
            if denominator == 0:
                yxb[proc] = "NA"
            else:
                yxb[proc] = frac_to_str(elapsed[proc] / denominator)
        self._recomputed["YXB_A"] = yxb["A"]
        self._recomputed["YXB_B"] = yxb["B"]
        self._recomputed["YXB_C"] = yxb["C"]
        self._recomputed["YXB_E"] = yxb["E"]
        if self._metrics is not None:
            for proc in PROCESSES:
                key = "YXB_" + proc
                if key in self._metrics:
                    if yxb[proc] != self._metrics[key]:
                        self._issue("C17", "metrics.%s" % key, yxb[proc],
                                    self._metrics[key],
                                    "recomputed YXB disagrees with the run metrics")
            if "yxb_denominator_h" in self._metrics and \
                    self._metrics["yxb_denominator_h"] != frac_to_str(denominator):
                self._issue("C17", "metrics.yxb_denominator_h", frac_to_str(denominator),
                            self._metrics["yxb_denominator_h"],
                            "recomputed YXB denominator disagrees with the run metrics")
            if "shift_count" in self._metrics and self._metrics["shift_count"] != shift_count:
                self._issue("C17", "metrics.shift_count", shift_count,
                            self._metrics["shift_count"], "shift_count mismatch")

    def _check_acceptance_and_metrics(self) -> None:
        """Recomputed T/S/PL/PW/YXB vs the frozen acceptance block and the run
        metrics."""
        if not self._structural_ok:
            return
        if self._T is not None:
            self._recomputed["T_h"] = frac_to_str(self._T)
            self._recomputed["T_ticks"] = hours_to_ticks(self._T, "T")
        if self._metrics is not None:
            for field in ("T", "S", "PL", "PW"):
                if field not in self._metrics:
                    continue
                recomputed = self._recomputed.get(field) if field != "T" \
                    else self._recomputed.get("T_h")
                if field == "T":
                    recomputed = self._recomputed.get("T_h")
                if str(recomputed) != str(self._metrics[field]):
                    self._issue("C17", "metrics.%s" % field, recomputed,
                                self._metrics[field],
                                "recomputed %s disagrees with the run metrics" % field)
        if self._acceptance is not None:
            for field in ("T", "S", "PL", "PW"):
                if field not in self._acceptance:
                    continue
                recomputed = self._recomputed.get("T_h") if field == "T" \
                    else self._recomputed.get(field)
                if str(recomputed) != str(self._acceptance[field]):
                    self._issue("C17", "acceptance.%s" % field, self._acceptance[field],
                                recomputed,
                                "recomputed %s disagrees with the frozen acceptance" % field)
            for proc in PROCESSES:
                key = "YXB_" + proc
                if key in self._acceptance and self._recomputed.get(key) is not None:
                    if self._recomputed[key] != self._acceptance[key]:
                        self._issue("C17", "acceptance.%s" % key, self._acceptance[key],
                                    self._recomputed[key],
                                    "recomputed YXB disagrees with the frozen acceptance")

    def _check_k9_special(self) -> None:
        """F8 / K9 authoritative read-only assertions (手算样例_K9跨班重测.md)."""
        if self._fixture_id != "F8" or not self._structural_ok:
            return

        def ticks(key: tuple, field: str) -> Optional[int]:
            view = self._tasks.get(key)
            if view is None:
                return None
            if field == "release":
                val = view["release_time"]
            elif field == "start":
                val = None
                if view["starts"]:
                    val = parse_hours(view["starts"][0].get("event_time"), "start")
            elif field == "finish":
                val = None
                if view["completes"]:
                    val = parse_hours(view["completes"][0].get("event_time"), "finish")
            else:
                return None
            return None if val is None else hours_to_ticks(val, field)

        def add(name: str, ok: bool, detail: str) -> None:
            self._special.append({"name": name, "ok": ok, "detail": detail})
            if not ok:
                self._issue("C08", "K9." + name, "assertion true", "false", detail)

        add("K9_T_84_ticks", self._recomputed.get("T_ticks") == 84,
            "T = 84 ticks = 14 h (got %s)" % self._recomputed.get("T_ticks"))
        add("K9_d3_B1_finish_51_ABNORMAL",
            ticks((3, "B", 1), "finish") == 51
            and self._scripted_outcomes.get((3, "B", 1)) == "ABNORMAL",
            "d3 B initial finish = 51 ticks (8.5h) ABNORMAL (got %s)" % ticks((3, "B", 1), "finish"))
        add("K9_d3_B2_release_51",
            ticks((3, "B", 2), "release") == 51,
            "d3 B retest release = 51 ticks (8.5h), never rewritten (got %s)"
            % ticks((3, "B", 2), "release"))
        add("K9_d3_B2_start_54", ticks((3, "B", 2), "start") == 54,
            "d3 B retest start = 54 ticks (9h), shift 2 (got %s)" % ticks((3, "B", 2), "start"))
        add("K9_d3_B2_finish_66", ticks((3, "B", 2), "finish") == 66,
            "d3 B retest finish = 66 ticks (11h) PASS (got %s)" % ticks((3, "B", 2), "finish"))
        add("K9_d3_B2_attempt_2",
            (3, "B", 2) in self._tasks and self._tasks[(3, "B", 2)]["starts"] and
            self._tasks[(3, "B", 2)]["starts"][0].get("effective_attempt_no") == 2,
            "d3 B retest effective_attempt_no = 2")
        add("K9_d3_E_start_66", ticks((3, "E", 1), "start") == 66,
            "d3 E start = 66 ticks (11h) (got %s)" % ticks((3, "E", 1), "start"))
        add("K9_d3_E_finish_84", ticks((3, "E", 1), "finish") == 84,
            "d3 E finish = 84 ticks (14h) (got %s)" % ticks((3, "E", 1), "finish"))
        add("K9_YXB_A_5_12", self._recomputed.get("YXB_A") == "5/12",
            "YXB_A = 7.5/18 = 5/12 (got %s)" % self._recomputed.get("YXB_A"))
        add("K9_YXB_B_4_9", self._recomputed.get("YXB_B") == "4/9",
            "YXB_B = 8/18 = 4/9 (got %s)" % self._recomputed.get("YXB_B"))
        add("K9_YXB_C_5_12", self._recomputed.get("YXB_C") == "5/12",
            "YXB_C = 7.5/18 = 5/12 (got %s)" % self._recomputed.get("YXB_C"))
        add("K9_YXB_E_1_2", self._recomputed.get("YXB_E") == "1/2",
            "YXB_E = 9/18 = 1/2 (got %s)" % self._recomputed.get("YXB_E"))
        add("K9_bay2_no_turnover",
            all(tv.get("bay_id") != 2 for tv in self._turnovers),
            "bay2 must be TERMINAL_OCCUPIED_UNTIL_STOP (no turnover for the last device)")

    # ------------------------------------------------------------------
    # entry point
    # ------------------------------------------------------------------

    def run(self) -> CheckReport:
        self._build_views()
        self._check_parameters_cross()
        self._check_shift_calendar()
        self._check_task_lifecycle()
        self._check_release_time()
        self._check_attempts()
        self._check_devices()
        self._check_turnovers()
        self._check_bay_coverage()
        self._check_resource_occupancy()
        self._check_same_timestamp_order()
        self._check_ledger_yxb()
        self._check_acceptance_and_metrics()
        self._check_k9_special()
        devices_summary: dict[str, Any] = {}
        for device_id in sorted(self._devices):
            dev = self._devices[device_id]
            devices_summary[str(device_id)] = {
                "terminal_state": dev["terminal_state"],
                "terminal_h": fmt_opt(dev["terminal_time"]),
                "d_state": dev["d_state"],
                "bay_id": dev["bay_id"],
            }
        self._recomputed["devices"] = devices_summary
        tasks_summary: dict[str, Any] = {}
        for key in sorted(self._tasks, key=lambda k: (k[0], PROCESS_ORDER[k[1]], k[2])):
            view = self._tasks[key]
            status = "COMPLETED" if view["completes"] else ("CANCELLED" if view["cancels"] else "RELEASED_UNFINISHED")
            finish = None
            if view["completes"]:
                finish = parse_hours(view["completes"][0].get("event_time"), "finish")
            elif view["cancels"]:
                finish = parse_hours(view["cancels"][0].get("event_time"), "cancel")
            outcome = None
            if view["observations"]:
                outcome = view["observations"][0].get("outcome")
            tasks_summary["D%03d_%s_%d" % key] = {
                "status": status,
                "release_h": fmt_opt(view["release_time"]),
                "start_h": fmt_opt(parse_hours(view["starts"][0].get("event_time"), "start"))
                if view["starts"] else None,
                "finish_h": fmt_opt(finish),
                "outcome": outcome,
            }
        self._recomputed["tasks"] = tasks_summary
        verdict = "PASS" if not self._issues else "FAIL"
        return CheckReport(
            fixture_id=self._fixture_id,
            scenario_id=self._cfg["scenario_id"],
            verdict=verdict,
            issues=self._issues,
            special_assertions=self._special,
            recomputed=self._recomputed,
            metadata={
                "registry_version": REGISTRY_VERSION,
                "check_ids": list(CHECK_IDS),
                "turnover_profile": self._cfg["turnover_profile"],
                "scenario": self._cfg["scenario"],
                "batch_size": self._cfg["batch_size"],
                "event_log_records": len(self._log),
                "task_package_ref": "G2-03-SPEC-V1.0.2",
            },
        )


# ---------------------------------------------------------------------------
# Module-level convenience API
# ---------------------------------------------------------------------------


def check_event_log(event_log: Any, config: dict, scripted: dict,
                    parameters: Optional[str] = None,
                    metrics: Optional[dict] = None) -> CheckReport:
    """Run the independent replay checker once and return its report."""
    return DesEventLogChecker(event_log, config, scripted,
                              parameters=parameters, metrics=metrics).run()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _load_json_or_jsonl(path: str) -> Any:
    try:
        with open(path, "r", encoding="utf-8") as handle:
            text = handle.read()
    except OSError as exc:
        raise CheckerValidationError("cannot read %s: %s" % (path, exc)) from exc
    stripped = text.lstrip()
    if stripped.startswith("["):
        return json.loads(text)
    records = []
    for line_no, line in enumerate(text.splitlines(), start=1):
        line = line.strip()
        if not line:
            continue
        try:
            records.append(json.loads(line))
        except json.JSONDecodeError as exc:
            raise CheckerValidationError(
                "invalid JSONL at %s line %d: %s" % (path, line_no, exc)) from exc
    return records


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="G2-04 independent event-log replay checker (CR-V3.1 C17/C19).")
    parser.add_argument("--event-log", required=True, help="immutable event_log (JSON array or JSONL)")
    parser.add_argument("--config", required=True, help="frozen des_config JSON")
    parser.add_argument("--fixture", required=True, help="scripted fixture record JSON")
    parser.add_argument("--parameters", default=None, help="shared parameters.csv")
    parser.add_argument("--metrics", default=None, help="optional run metrics JSON")
    parser.add_argument("--report", default=None, help="optional output path for the report JSON")
    args = parser.parse_args(argv)
    try:
        event_log = _load_json_or_jsonl(args.event_log)
        with open(args.config, "r", encoding="utf-8") as handle:
            config = json.load(handle)
        with open(args.fixture, "r", encoding="utf-8") as handle:
            fixture = json.load(handle)
        metrics = None
        if args.metrics:
            with open(args.metrics, "r", encoding="utf-8") as handle:
                metrics = json.load(handle)
        report = check_event_log(event_log, config, fixture,
                                 parameters=args.parameters, metrics=metrics)
        output = json.dumps(report.to_dict(), ensure_ascii=False, indent=2, sort_keys=True)
        if args.report:
            with open(args.report, "w", encoding="utf-8") as handle:
                handle.write(output + "\n")
        else:
            print(output)
        return 0 if report.verdict == "PASS" else 1
    except NonIntegerTickError as exc:
        print("CHECKER_TICK_ERROR: %s" % exc, file=sys.stderr)
        return 1
    except CheckerValidationError as exc:
        print("CHECKER_VALIDATION_ERROR: %s" % exc, file=sys.stderr)
        return 2
    except CheckerNumericalError as exc:
        print("CHECKER_NUMERICAL_ERROR: %s" % exc, file=sys.stderr)
        return 3
    except OSError as exc:
        print("CHECKER_IO_ERROR: %s" % exc, file=sys.stderr)
        return 4
    except json.JSONDecodeError as exc:
        print("CHECKER_JSON_ERROR: %s" % exc, file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
