#!/usr/bin/env python3
"""Q3-H2-P3-C action-stability diagnostics runner (SPEC 4 / D-10, frozen).

Data domain (strict): namespace = h2_tuning, master_seed = 6, K = 10.5,
replicate_ids = 0..9.  NOT h2_holdout / q3_formal / development_unit
physical results (stability uses the h2-side physical worlds generated by
the continuation engine under h2_tuning post keys).

B-1 sample: from tuning batches 0..9, ALL H2-eligible decision points in
batch order then intra-batch time order:
  * first 50 wait-eligible (incl. both);
  * first 50 PM-eligible (PM-only);
  * if a class has <50, take all and top up from the other class in frozen
    order; total sample cap 120.  actual n / wait n / PM-only n / both
    coverage must be reported.

Hard gates:
  * n < 50 -> H2 = DELETE / INSUFFICIENT_STABILITY_SAMPLE (immutable
    negative evidence, STOP);
  * (a) determinism: same observable/posterior/config/keys -> same decision
    points / evaluated set / Q_hat / SE / action (C23 hidden variants do
    not change the action);
  * (b) ALT-salt agreement >= 0.95 (point estimate = the only hard gate;
    Clopper-Pearson 95% interval reported as disclosure only);
  * (c) M vs 2M agreement >= 0.95 (M=16 offline diagnostic only; frozen
    production M*=8 unchanged);
  * deviation rate: if deviation_count == 0 -> H2_NO_EFFECTIVE_DEVIATION
    -> DELETE (SPEC 4/13; never lower the 2SE threshold to create
    deviations);
  * C23 PASS required;
  * budget: all offline rollouts + wallclock appended to the ledger.

Outputs (immutable root 05_结果/H2/tuning/stability/run_<UTC>_<8hex>/):
bootstrap_spec_snapshot.md, task_package_snapshot.yaml, commands.json,
environment.json, scope_audit.json, sample_selection_report.json,
stability_b_report.json, stability_c_report.json, deviation_report.json,
c23_policy_report.json, rollout_accounting_report.json, result_summary.json,
test_report.json, regression_report.json, evidence_semantic_mapping_report,
input_hashes.json, dev_budget_ledger_snapshot.json,
C21_REQUALIFICATION_REPORT.json, checks.json, run_manifest.json,
file_hashes.sha256.  The root is verified fail-closed (acyclic hash DAG
RULE A + manifest/inventory consistency + semantic mapping) in a
probe/confirm/promote/final cycle before it is promoted.

Python 3.12, standard library only.
"""
from __future__ import annotations

import io
import json
import math
import secrets
import shutil
import sys
import time
import unittest
from datetime import datetime, timezone
from fractions import Fraction
from pathlib import Path
from typing import Any, Optional

BASE_DIR = Path(__file__).resolve().parents[2]
CODE_DIR = BASE_DIR / "04_代码"
MAIN_MODEL = CODE_DIR / "main_model"
for _entry in (str(MAIN_MODEL), str(CODE_DIR)):
    if _entry not in sys.path:
        sys.path.insert(0, _entry)

from scripts import run_q3_h1_formal_v1 as frm  # noqa: E402
from main_model.h2 import observable_state_v1 as obs  # noqa: E402
from main_model.h2 import posterior_state_v1 as ps  # noqa: E402
from main_model.h2 import continuation_v1 as cont  # noqa: E402
from main_model.h2 import decision_point_v1 as dpimpl  # noqa: E402
from main_model.h2_rollout import rollout_engine_v1 as re1  # noqa: E402
from main_model.h2_rollout import post_keys_v1 as pk  # noqa: E402
from main_model.h2_rollout import h2_batch_runner_v1 as br  # noqa: E402
from main_model.h2_rollout import h2_policy_v1 as pol  # noqa: E402

PACKAGE_REF = "Q3-H2-P3-C"
BOOTSTRAP_SPEC_FILE = frm.BOOTSTRAP_SPEC_FILE
FORMAL_TASK_PACKAGE_FILE = frm.TASK_PACKAGE_FILE
FORMAL_TASK_PACKAGE_SHA = frm.TASK_PACKAGE_SNAPSHOT_SHA
REGISTRY_VERSION = "CR-V3.1"

NS = "h2_tuning"
MASTER_SEED = 6
REPLICATES = tuple(range(10))       # 0..9
K = Fraction(21, 2)                 # 10.5
BATCH_SIZE = 100
M_STAR = pol.M_STAR                 # 8
ALT_SALT = "q3h2-bootstrap-alt-v1"
WAIT_CAP = 50
PM_CAP = 50
SAMPLE_CAP = 120
AGREEMENT_GATE = 0.95

SCOPE_AUDIT = {
    "package": PACKAGE_REF,
    "data_domain": {"namespace": NS, "master_seed": MASTER_SEED,
                    "K": "10.5", "replicate_ids": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]},
    "b1_sample": "first 50 wait-eligible + first 50 PM-only in batch/time "
                 "order; cap 120; top-up across classes; actual n reported",
    "stability_a": "determinism (same observable/posterior/config/keys -> "
                   "same decision points / Q_hat / SE / action; C23 hidden "
                   "variants do not change the action)",
    "stability_b": "ALT-salt agreement >= 0.95 point estimate (only hard "
                   "gate); Clopper-Pearson 95% interval = disclosure only",
    "stability_c": "M*=8 vs 2M*=16 agreement >= 0.95 (offline diagnostic; "
                   "production M*=8 unchanged)",
    "deviation_rate": "reported; deviation_count == 0 -> "
                      "H2_NO_EFFECTIVE_DEVIATION -> DELETE",
    "h2_holdout": "NOT USED", "q3_formal": "NOT USED",
    "development_unit_physical": "NOT USED (stability uses h2-side "
                                 "h2_tuning physical worlds)",
    "c25": "NOT AUTHORIZED", "q3_k_recommendation": "NO",
    "new_formal_worlds": "NO", "new_holdout_worlds": "NO",
}

REGRESSION_PATTERNS = (
    "test_h2_p1_firewall_v1.py",
    "test_h2_q3_density_v1.py",
    "test_g3_key_schema_v1.py",
    "test_q3_h1_formal_v1.py",
    "test_g3_random_des_v1.py",
    "test_h2_p3b_v1.py",
)

PRIMARY_TEST_PATTERN = "test_h2_p3c_v1.py"

# semantic evidence mapping: report file -> frozen check id (mirror of the
# P3-B runner's REPORT_MAPPING; the mapping check is fail-closed).
P3C_REPORT_MAPPING: dict[str, str] = {
    "B1_SAMPLE_SELECTION": "sample_selection_report.json",
    "STABILITY_B": "stability_b_report.json",
    "STABILITY_C": "stability_c_report.json",
    "DEVIATION": "deviation_report.json",
    "C23_POLICY": "c23_policy_report.json",
    "ROLLOUT_ACCOUNTING": "rollout_accounting_report.json",
    "EVIDENCE_SEMANTIC_MAPPING": "evidence_semantic_mapping_report.json",
}


# ---------------------------------------------------------------------------
# tuning-batch world generation (h2-side physical worlds)
# ---------------------------------------------------------------------------


def _fresh_batch_state(rep: int):
    """Build the t=0 ObservableState / PosteriorState / ContinuationWorld
    for a fresh 100-device batch under h2_tuning."""
    log = [
        {"event_type": "TRUE_STATE_GENERATED", "event_time": "0",
         "device_id": 1, "true_state": {"A": False, "B": False, "C": False}},
        {"event_type": "TRUE_STATE_GENERATED", "event_time": "0",
         "device_id": 2, "true_state": {"A": False, "B": False, "C": False}},
        {"event_type": "SHIFT_CHANGE", "event_time": "0", "shift_index": 0,
         "shift_start": "0", "shift_end": "300", "on_duty_squad": 0,
         "squad_id": 0},
    ]
    st = obs.project_log_prefix(log, Fraction(0), batch_size=BATCH_SIZE)
    post = ps.PosteriorState.from_observable(st)
    prov = pk.physical_post_provider(NS, MASTER_SEED, rep, BATCH_SIZE,
                                     ("A", "B", "C", "E"))
    # hidden truth for the two preloaded devices from the physical prior
    ux = {1: prov.u_x(1), 2: prov.u_x(2)}
    ud = {1: prov.u_d(1), 2: prov.u_d(2)}
    ul = {r: prov.u_l(r, 1) for r in ("A", "B", "C", "E")}
    world = cont.rebuild_continuation_world(st, post, ux, ud, ul)
    return st, post, world, prov


def generate_tuning_batch(rep: int, cfg: re1.RolloutConfig
                          ) -> dict[str, Any]:
    """Run one h2_tuning physical batch under the H1 baseline (no H2
    policy)."""
    st, post, world, prov = _fresh_batch_state(rep)
    eng = br.H2BatchRunner(st, post, world, prov, cfg, None, MASTER_SEED, rep,
                           policy_enabled=False)
    t0 = time.perf_counter()
    out = eng.run()
    wall = time.perf_counter() - t0
    return {"rep": rep, "t_end": out.t_end, "events": list(out.events),
            "wallclock_s": wall,
            "passed": out.devices_passed, "exited": out.devices_exited}


def collect_eligible_points(batch_log: list[dict], K: Fraction,
                            batch_size: int
                            ) -> list[dict[str, Any]]:
    """All H2-eligible decision points of a batch, in time order."""
    pts = dpimpl.reconstruct_decision_points(batch_log, K,
                                             batch_size=batch_size,
                                             t_end=Fraction(10 ** 9))
    out = []
    for p in pts:
        wait_legal = dpimpl.A_WAIT_EVENT in p.legal_actions
        pm_legal = (dpimpl.A_PM_WITH_HEAD in p.legal_actions
                    or dpimpl.A_PM_IDLE in p.legal_actions)
        if not (wait_legal or pm_legal):
            continue
        out.append({
            "time": p.time, "resource": p.resource, "kind": p.kind,
            "legal_actions": list(p.legal_actions),
            "wait_legal": wait_legal, "pm_legal": pm_legal,
            "is_both": wait_legal and pm_legal,
            "wait_anchor_time": (p.wait_anchor.completion_time
                                 if p.wait_anchor is not None else None),
            "quota_class": ("WAIT" if wait_legal else "PM"),
        })
    out.sort(key=lambda x: (x["time"], x["resource"]))
    return out


def build_b1_sample(batches: list[list[dict]], K: Fraction, batch_size: int
                    ) -> dict[str, Any]:
    """Deterministic B-1 sample: batch order then intra-batch time order,
    first 50 wait-eligible + first 50 PM-only; cap 120."""
    wait_pts: list[dict] = []
    pm_pts: list[dict] = []
    for bi, blog in enumerate(batches):
        for p in collect_eligible_points(blog, K, batch_size):
            p["batch"] = bi
            if p["quota_class"] == "WAIT":
                if len(wait_pts) < WAIT_CAP:
                    wait_pts.append(p)
            else:
                if len(pm_pts) < PM_CAP:
                    pm_pts.append(p)
    sample = wait_pts + pm_pts
    if len(sample) > SAMPLE_CAP:
        sample = sample[:SAMPLE_CAP]
    # deterministic per-point dp index (0-based across the diagnostic
    # sample; SPEC 6.2 dp = 0-based decision-point index -- for the offline
    # diagnostics the index is the sample position so CRN keys are stable
    # across salt / M evaluations of the same point).
    for idx, p in enumerate(sample):
        p["dp"] = idx
    n_wait = len(wait_pts)
    n_pm = len(pm_pts)
    n_both = sum(1 for p in sample if p["is_both"])
    return {"n": len(sample), "n_wait": n_wait, "n_pm": n_pm,
            "n_both": n_both, "wait_cap": WAIT_CAP, "pm_cap": PM_CAP,
            "sample_cap": SAMPLE_CAP, "points": sample}


# ---------------------------------------------------------------------------
# stability evaluations
# ---------------------------------------------------------------------------


def _point_context(p: dict, batch_log: list[dict], batch_size: int):
    """Build (state, posterior, world, cfg, log_prefix) for one sample
    point, evaluating from the observable prefix AT the point's time."""
    t = p["time"]
    prefix = [r for r in batch_log
              if Fraction(r["event_time"]) <= t]
    st = obs.project_log_prefix(prefix, t, batch_size=batch_size)
    post = ps.PosteriorState.from_observable(st)
    prov = pk.physical_post_provider(NS, MASTER_SEED, p["batch"], batch_size,
                                     ("A", "B", "C", "E"))
    ux = {d.device_id: prov.u_x(d.device_id) for d in st.devices}
    ud = {d.device_id: prov.u_d(d.device_id) for d in st.devices}
    ul = {r: prov.u_l(r, 1) for r in ("A", "B", "C", "E")}
    world = cont.rebuild_continuation_world(st, post, ux, ud, ul)
    cfg = re1.RolloutConfig(batch_size=batch_size,
                            shift_length_h=K, shifts_per_day=2,
                            scenario="q3_two_shift",
                            tau_pm=re1.NO_PM_BEFORE_MANDATORY)
    return {"state": st, "posterior": post, "world": world,
            "provider": prov, "cfg": cfg, "log_prefix": prefix}


def _cp95_binomial(x: int, n: int) -> tuple[float, float]:
    """Exact Clopper-Pearson 95% two-sided interval (disclosure only)."""
    if n == 0:
        return (0.0, 1.0)
    if x == 0:
        return (0.0, 1 - (0.025) ** (1 / n))
    if x == n:
        return ((0.025) ** (1 / n), 1.0)
    lo = _cp_lower(x, n)
    hi = _cp_upper(x, n)
    return (lo, hi)


def _cp_lower(x: int, n: int) -> float:
    """Clopper-Pearson lower bound: p_lo solves P(X <= x-1 | p_lo) = 0.975
    (pbinom is decreasing in p, so pbinom >= 0.975 means p < p_lo)."""
    lo = 0.0
    hi = float(x) / n
    for _ in range(60):
        mid = (lo + hi) / 2
        if _pbinom(x - 1, n, mid) >= 0.975:
            lo = mid
        else:
            hi = mid
    return (lo + hi) / 2


def _cp_upper(x: int, n: int) -> float:
    """Clopper-Pearson upper bound: p_hi solves P(X <= x | p_hi) = 0.025
    (pbinom <= 0.025 means p > p_hi)."""
    lo = float(x) / n
    hi = 1.0
    for _ in range(60):
        mid = (lo + hi) / 2
        if _pbinom(x, n, mid) <= 0.025:
            hi = mid
        else:
            lo = mid
    return (lo + hi) / 2


def _pbinom(x: int, n: int, p: float) -> float:
    import math
    if p <= 0:
        return 1.0 if x >= n else 0.0
    if p >= 1:
        return 0.0
    total = 0.0
    for k in range(0, x + 1):
        total += math.comb(n, k) * (p ** k) * ((1 - p) ** (n - k))
    return total


def evaluate_sample(sample: dict, batches: list[list[dict]],
                    salt: str, M: int, batch_size: int
                    ) -> dict[str, Any]:
    """Evaluate the B-1 sample with a given salt / M; return chosen actions
    + deviation info."""
    rows = []
    chosen = []
    n_dev = 0
    dev_types: dict[str, int] = {}
    for p in sample["points"]:
        ctx = _point_context(p, batches[p["batch"]], batch_size)
        dec = pol.evaluate_decision_point(
            ctx["state"], ctx["posterior"], ctx["world"], ctx["provider"],
            ctx["cfg"], p["dp"], p["resource"], p["kind"],
            p["quota_class"], tuple(p["legal_actions"]), ctx["log_prefix"],
            MASTER_SEED, p["batch"], wait_anchor_time=p.get("wait_anchor_time"),
            M=M, salt=salt)
        chosen.append(dec.chosen)
        if dec.deviated:
            n_dev += 1
            dev_types[dec.chosen] = dev_types.get(dec.chosen, 0) + 1
        rows.append({"point": p, "chosen": dec.chosen,
                     "deviated": dec.deviated,
                     "estimates": {a: e.to_canonical_dict()
                                   for a, e in sorted(dec.estimates.items())}})
    n = len(chosen)
    return {"n": n, "chosen": chosen, "rows": rows,
            "n_deviated": n_dev,
            "deviation_rate": (n_dev / n) if n else 0.0,
            "deviation_types": dev_types}


def stability_b(normal: dict, alt: dict) -> dict[str, Any]:
    n = normal["n"]
    matched = sum(1 for a, b in zip(normal["chosen"], alt["chosen"])
                  if a == b)
    agreement = matched / n if n else 0.0
    lo, hi = _cp95_binomial(matched, n)
    return {"n": n, "matched": matched, "agreement": agreement,
            "cp95_lo": lo, "cp95_hi": hi,
            "gate": AGREEMENT_GATE,
            "status": "PASS" if agreement >= AGREEMENT_GATE else "FAIL",
            "gate_type": "point-estimate-only; CP interval = disclosure"}


def stability_c(m8: dict, m16: dict) -> dict[str, Any]:
    n = m8["n"]
    matched = sum(1 for a, b in zip(m8["chosen"], m16["chosen"])
                  if a == b)
    agreement = matched / n if n else 0.0
    lo, hi = _cp95_binomial(matched, n)
    return {"n": n, "matched": matched, "agreement": agreement,
            "cp95_lo": lo, "cp95_hi": hi,
            "gate": AGREEMENT_GATE,
            "status": "PASS" if agreement >= AGREEMENT_GATE else "FAIL",
            "gate_type": "point-estimate-only; CP interval = disclosure",
            "note": "M=16 offline diagnostic only; production M*=8 unchanged"}


def _run_suite(pattern: str) -> dict[str, Any]:
    loader = unittest.TestLoader()
    suite = loader.discover(str(CODE_DIR / "tests"), pattern=pattern)
    buf = io.StringIO()
    runner = unittest.TextTestRunner(stream=buf, verbosity=1)
    result = runner.run(suite)
    return {
        "command": f"python -m unittest discover -s tests -p {pattern!r}",
        "exit_code": 0 if result.wasSuccessful() else 1,
        "tests_run": result.testsRun,
        "failures": len(result.failures),
        "errors": len(result.errors),
        "ok": result.wasSuccessful(),
        "log_tail": buf.getvalue()[-1500:],
    }


def _new_run_id() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ_") + secrets.token_hex(4)


def _sha256_file(path: Path) -> str:
    return frm._sha256_file(path)


def _sha256_bytes(data: bytes) -> str:
    import hashlib
    return hashlib.sha256(data).hexdigest()


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _dump_json(path: Path, value: Any) -> None:
    Path(path).write_text(
        json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        + "\n", encoding="utf-8", newline="\n")


def _promote(staging: Path, final: Path) -> dict[str, Any]:
    if final.exists():
        shutil.rmtree(final)
    shutil.copytree(staging, final)
    mismatches = []
    for p in sorted(staging.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(staging)
        q = final / rel
        if not q.is_file() or _sha256_file(p) != _sha256_file(q):
            mismatches.append(rel.as_posix())
    return {"ok": len(mismatches) == 0,
            "files_copied": sum(1 for p in staging.rglob("*") if p.is_file()),
            "sha_mismatches": mismatches}


def _jsonable(value: Any) -> Any:
    """Recursively convert Fraction -> str for JSON serialization."""
    if isinstance(value, Fraction):
        return str(value)
    if isinstance(value, dict):
        return {k: _jsonable(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_jsonable(v) for v in value]
    return value


def evidence_mapping_check(evidence_dir: Path) -> dict[str, Any]:
    """Fail-closed semantic mapping: every frozen report file exists and
    carries its frozen check id."""
    results: dict[str, Any] = {}
    ok = True
    for check_id, fname in P3C_REPORT_MAPPING.items():
        p = evidence_dir / fname
        if not p.is_file():
            results[fname] = {"ok": False, "expected": check_id,
                              "got": None, "missing": True}
            ok = False
            continue
        try:
            data = json.loads(p.read_text(encoding="utf-8"))
            got = data.get("check") or data.get("id")
        except (json.JSONDecodeError, OSError) as exc:
            results[fname] = {"ok": False, "expected": check_id,
                              "got": None, "error": str(exc)}
            ok = False
            continue
        match = got == check_id
        ok = ok and match
        results[fname] = {"ok": match, "expected": check_id, "got": got}
    return {"check": "EVIDENCE_SEMANTIC_MAPPING",
            "status": "PASS" if ok else "FAIL", "files": results}


def _verify(out_dir: Path) -> dict[str, Any]:
    """Fail-closed verification of an evidence root (probe/confirm/final):
    acyclic hash DAG (RULE A) + manifest/inventory/actual SHA consistency
    + semantic evidence mapping.  Raises->FAIL on any inconsistency."""
    try:
        dag = frm.verify_hash_dag(out_dir)
        cons = frm.verify_manifest_inventory_consistency(out_dir)
        mapping = evidence_mapping_check(out_dir)
        ok = (dag["hash_graph_acyclic"] is True and dag["mismatches"] == 0
              and "PASS" in cons["manifest_output_hashes"]
              and "PASS" in cons["manifest_inventory_crosscheck"]
              and cons["c21_report_sha_consistency"] == "PASS"
              and mapping["status"] == "PASS")
        return {"ok": ok, "hash_graph_acyclic": dag["hash_graph_acyclic"],
                "inventory_n": dag["inventory_n"], "mismatches": dag["mismatches"],
                "manifest_output_hashes": cons["manifest_output_hashes"],
                "manifest_inventory_crosscheck": cons["manifest_inventory_crosscheck"],
                "c21_report_sha_consistency": cons["c21_report_sha_consistency"],
                "evidence_semantic_mapping": mapping["status"],
                "detail": {"dag": dag, "consistency": cons, "mapping": mapping}}
    except AssertionError as exc:
        return {"ok": False, "error": f"AssertionError: {exc}"}


def _input_hashes() -> dict[str, str]:
    paths = {
        "bootstrap_spec": BOOTSTRAP_SPEC_FILE,
        "formal_task_package": FORMAL_TASK_PACKAGE_FILE,
        "problem_contract": frm.PROBLEM_CONTRACT_FILE,
        "parameters_csv": frm.PARAMETERS_CSV,
        "registry": BASE_DIR / "01_审计" / "检查注册表_V3.1.md",
        "observable_state": MAIN_MODEL / "h2" / "observable_state_v1.py",
        "posterior_state": MAIN_MODEL / "h2" / "posterior_state_v1.py",
        "decision_point": MAIN_MODEL / "h2" / "decision_point_v1.py",
        "action_semantics": MAIN_MODEL / "h2" / "action_semantics_v1.py",
        "rollout_seed": MAIN_MODEL / "h2" / "rollout_seed_v1.py",
        "continuation": MAIN_MODEL / "h2" / "continuation_v1.py",
        "quota_selector": MAIN_MODEL / "h2" / "quota_selector_v1.py",
        "q_estimator": MAIN_MODEL / "h2" / "q_estimator_v1.py",
        "rollout_engine": MAIN_MODEL / "h2_rollout" / "rollout_engine_v1.py",
        "post_keys": MAIN_MODEL / "h2_rollout" / "post_keys_v1.py",
        "h2_policy": MAIN_MODEL / "h2_rollout" / "h2_policy_v1.py",
        "batch_runner": MAIN_MODEL / "h2_rollout" / "h2_batch_runner_v1.py",
        "runner": Path(__file__).resolve(),
    }
    for pat in REGRESSION_PATTERNS + (PRIMARY_TEST_PATTERN,):
        paths[pat] = CODE_DIR / "tests" / pat
    return {name: _sha256_file(p) for name, p in paths.items()}


def _rollout_count(ev: dict[str, Any], M: int) -> int:
    """Actual rollout count = sum over evaluated points of
    (#legal actions x M) (not 3 x M per point: some points have 1-2
    legal actions)."""
    return sum(len(row["estimates"]) for row in ev["rows"]) * M


def _build_evidence(out_dir: Path, run_id: str, checks: dict[str, Any],
                    test_report: dict[str, Any],
                    regressions: list[dict[str, Any]],
                    verification: Optional[dict[str, Any]],
                    wall_total: float,
                    sample: dict[str, Any], b_res: dict[str, Any],
                    c_res: dict[str, Any], dev_report: dict[str, Any],
                    c23_policy: dict[str, Any],
                    ev_normal: dict[str, Any], ev_alt: dict[str, Any],
                    ev_m16: dict[str, Any],
                    gen_rows: list[dict[str, Any]], gen_wall: float,
                    final_status: str) -> None:
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    spec_bytes = Path(BOOTSTRAP_SPEC_FILE).read_bytes()
    spec_sha = _sha256_bytes(spec_bytes)
    (out_dir / "bootstrap_spec_snapshot.md").write_bytes(spec_bytes)
    (out_dir / "task_package_snapshot.yaml").write_text(
        "# Q3-H2-P3-C task-package snapshot\n"
        f"package_ref: {PACKAGE_REF}\n"
        "authority: Q3_H2_BOOTSTRAP_SPEC_DRAFT.md FINAL_FREEZE_ACCEPTED "
        "sections 4 (action stability) / 4.1 (cross-K transfer: NOT run "
        "here) / 5 / 6 / 13 / 17.2 + Q3-H2-P3-C Human Gate authorization "
        "(starting HEAD c271a62)\n"
        f"bootstrap_spec_snapshot: bootstrap_spec_snapshot.md\n"
        f"bootstrap_spec_sha256: {spec_sha}\n"
        f"formal_task_package_sha256: {FORMAL_TASK_PACKAGE_SHA}\n"
        "p1: FINAL PASS / ACCEPTED (08488e4)\n"
        "p2: FINAL PASS / ACCEPTED (a5d2faf)\n"
        "p3a: FINAL PASS / ACCEPTED (fcf07f6)\n"
        "p3b: FINAL PASS / ACCEPTED (c271a62; M*=8, C_eval*=8, W_cap*=4, "
        "P_cap*=4 frozen)\n"
        "p3c: action stability (b)(c) + deviation rate + C23 policy "
        "diagnostics on the frozen policy; cross-K transfer / h2_holdout / "
        "C25 NOT run here\n"
        "evidence_rule: ACYCLIC hash DAG (RULE A)\n",
        encoding="utf-8", newline="\n")
    _dump_json(out_dir / "commands.json", {
        "run_id": run_id,
        "command": "python 04_代码/scripts/run_h2_p3c_stability_v1.py",
        "wall_clock_s": round(wall_total, 2)})
    _dump_json(out_dir / "environment.json", frm._env_summary())
    _dump_json(out_dir / "scope_audit.json", SCOPE_AUDIT)
    _dump_json(out_dir / "test_report.json", test_report)
    _dump_json(out_dir / "regression_report.json", {
        "regressions": regressions,
        "note": "deterministic suites; commands/exit codes/test counts "
                "truthfully recorded"})
    _dump_json(out_dir / "sample_selection_report.json",
               _jsonable({**sample, "check": "B1_SAMPLE_SELECTION",
                          "id": "B1_SAMPLE_SELECTION"}))
    _dump_json(out_dir / "stability_b_report.json",
               {**b_res, "check": "STABILITY_B", "id": "STABILITY_B"})
    _dump_json(out_dir / "stability_c_report.json",
               {**c_res, "check": "STABILITY_C", "id": "STABILITY_C"})
    _dump_json(out_dir / "deviation_report.json",
               {**dev_report, "check": "DEVIATION", "id": "DEVIATION"})
    _dump_json(out_dir / "c23_policy_report.json",
               {**c23_policy, "id": "C23_POLICY"})
    _dump_json(out_dir / "rollout_accounting_report.json", {
        "check": "ROLLOUT_ACCOUNTING", "id": "ROLLOUT_ACCOUNTING",
        "tuning_batches": gen_rows,
        "tuning_generation_wallclock_s": round(gen_wall, 4),
        "stability_evaluations": {
            "normal_salt_M8": {"n_points": ev_normal["n"],
                               "rollouts": _rollout_count(ev_normal, M_STAR)},
            "alt_salt_M8": {"n_points": ev_alt["n"],
                            "rollouts": _rollout_count(ev_alt, M_STAR)},
            "m16": {"n_points": ev_m16["n"],
                    "rollouts": _rollout_count(ev_m16, 2 * M_STAR)}},
        "per_batch_C_rollout_max": 0,
        "note": "offline diagnostics; not subject to the online C_rollout "
                "cap (which applies to the batch driver runs)"})
    _dump_json(out_dir / "result_summary.json", {
        "source_run_id": run_id,
        "sample_n": sample["n"], "sample_wait": sample["n_wait"],
        "sample_pm": sample["n_pm"], "sample_both": sample["n_both"],
        "agreement_b": b_res["agreement"], "cp95_b": [b_res["cp95_lo"],
                                                      b_res["cp95_hi"]],
        "agreement_c": c_res["agreement"], "cp95_c": [c_res["cp95_lo"],
                                                      c_res["cp95_hi"]],
        "deviation_rate": dev_report["deviation_rate"],
        "deviation_types": dev_report["deviation_types"],
        "c23_policy": c23_policy["status"],
        "final_status": final_status})
    mapping_result = evidence_mapping_check(out_dir)
    _dump_json(out_dir / "evidence_semantic_mapping_report.json",
               mapping_result)
    ledger_path = BASE_DIR / "05_结果" / "H2" / "dev_budget_ledger.json"
    if ledger_path.is_file():
        _dump_json(out_dir / "dev_budget_ledger_snapshot.json",
                   json.loads(ledger_path.read_text(encoding="utf-8")))
    _dump_json(out_dir / "input_hashes.json", _input_hashes())

    verify_ok = verification is not None and verification.get("ok") is True
    c21a = ("PASS" if verify_ok else
            ("PENDING_PROBE" if verification is None else "FAIL"))
    gates_ok = checks["overall"] == "PASS"
    overall_ok = (gates_ok and test_report["ok"]
                  and all(r["ok"] for r in regressions) and verify_ok)
    _dump_json(out_dir / "C21_REQUALIFICATION_REPORT.json", {
        "run_id": run_id, "check_id": "CR-V3.1/C21",
        "scope": "Q3-H2-P3-C action stability evidence root",
        "status": "PASS" if overall_ok else "FAIL",
        "verification": verification,
        "items": [
            {"id": "C21a", "status": c21a,
             "note": "acyclic hash inventory (RULE A); status from the "
                     "actual verifier"},
            {"id": "C21b", "status": c21a,
             "note": "manifest/inventory/actual SHA consistency; status "
                     "from the actual verifier"},
            {"id": "C21c", "status": "PASS" if overall_ok else "FAIL",
             "note": "P3-C stability (b)(c) gates + deviation + C23 policy "
                     "+ tests + regressions"}]})
    _dump_json(out_dir / "checks.json", {
        "run_id": run_id, "registry_version": REGISTRY_VERSION,
        "overall_status": "PASS" if overall_ok else "FAIL",
        "verification_fail_closed": {
            "hash_graph_acyclic": verification.get("hash_graph_acyclic")
            if verification else None,
            "inventory_mismatches": verification.get("mismatches")
            if verification else None,
            "manifest_inventory_consistency": verification.get(
                "manifest_inventory_crosscheck") if verification else None,
            "c21_report_sha_consistency": verification.get(
                "c21_report_sha_consistency") if verification else None,
            "evidence_semantic_mapping": verification.get(
                "evidence_semantic_mapping") if verification else None},
        "items": [
            {"check_id": c["check"], "status": c["status"]}
            for c in checks["checks"]] +
            [{"check_id": "TESTS", "status": "PASS" if test_report["ok"]
              else "FAIL",
              "count": f"{test_report['tests_run'] - test_report['failures'] - test_report['errors']}"
                       f"/{test_report['tests_run']}"},
             {"check_id": "REGRESSIONS", "status": "PASS" if all(
                 r["ok"] for r in regressions) else "FAIL",
              "detail": [{"pattern": r["command"].split("'")[1],
                          "exit_code": r["exit_code"],
                          "tests_run": r["tests_run"]}
                         for r in regressions]},
             {"check_id": "CR-V3.1/C21", "status": "PASS" if overall_ok
              else "FAIL",
              "note": "acyclic hash inventory + manifest/inventory "
                      "consistency (fail-closed)"}]})

    artifacts = [
        {"path": p.relative_to(out_dir).as_posix(),
         "bytes": p.stat().st_size, "sha256": _sha256_file(p)}
        for p in sorted(out_dir.rglob("*"))
        if p.is_file() and p.name != "file_hashes.sha256"]
    _dump_json(out_dir / "run_manifest.json", {
        "run_id": run_id, "created_at": _utc_now(), "gate": "Q3",
        "purpose": "h2_p3c_action_stability", "formal": True,
        "label": "Q3-H2-P3-C action stability diagnostics (SPEC 4 / D-10)",
        "paper_authoritative": False,
        "task_package_ref": PACKAGE_REF,
        "task_package_snapshot_path": "task_package_snapshot.yaml",
        "bootstrap_spec_sha256": spec_sha,
        "formal_task_package_sha256": FORMAL_TASK_PACKAGE_SHA,
        "registry_version": REGISTRY_VERSION,
        "hash_inventory_path": "file_hashes.sha256",
        "hash_inventory_rule": (
            "ACYCLIC DAG (RULE A): run_manifest does not hash "
            "file_hashes.sha256; file_hashes covers all artifacts incl. "
            "run_manifest and task_package_snapshot, never itself."),
        "random_domain": {
            "stability_diagnostics": {
                "namespace": "h2_tuning", "master_seed": MASTER_SEED,
                "replicate_ids": list(REPLICATES), "K": "10.5",
                "purpose": "P3-C action stability (b)(c) + deviation rate "
                           "+ C23 policy only",
                "rollout_namespace": "h2_rollout (rollout post keys; salts "
                                     "q3h2-bootstrap-v1 / "
                                     "q3h2-bootstrap-alt-v1)",
                "h2_holdout_used": False, "q3_formal_used": False,
                "development_unit_physical_used": False,
                "new_formal_worlds": False, "new_holdout_worlds": False}},
        "p1": "FINAL PASS / ACCEPTED (08488e4)",
        "p2": "FINAL PASS / ACCEPTED (a5d2faf)",
        "p3a": "FINAL PASS / ACCEPTED (fcf07f6)",
        "p3b": "FINAL PASS / ACCEPTED (c271a62; M*=8, C_eval*=8, W_cap*=4, "
               "P_cap*=4 frozen)",
        "p3c": {
            "agreement_b": b_res["agreement"], "cp95_b": [b_res["cp95_lo"],
                                                          b_res["cp95_hi"]],
            "agreement_c": c_res["agreement"],
            "deviation_count": dev_report["deviation_count"],
            "deviation_rate": dev_report["deviation_rate"],
            "c23_policy": c23_policy["status"],
            "final_status": final_status,
            "action_stability": b_res["status"], "m_vs_2m": c_res["status"],
            "cross_k_transfer": "NOT RUN",
            "h2_holdout": "NOT RUN", "c25": "NOT RUN"},
        "verification_fail_closed": (
            verification if verification is not None else "PROBE_PHASE"),
        "overall_status": "PASS" if overall_ok else "FAIL",
        "environment": frm._env_summary(), "outputs": artifacts,
        "check_report_paths": [
            "checks.json", "sample_selection_report.json",
            "stability_b_report.json", "stability_c_report.json",
            "deviation_report.json", "c23_policy_report.json",
            "rollout_accounting_report.json", "result_summary.json",
            "regression_report.json", "test_report.json", "scope_audit.json",
            "C21_REQUALIFICATION_REPORT.json"],
        "notes": [
            "Q3-H2-P3-C：在冻结 H2 政策（M*=8, C_eval*=8, W_cap*=4, "
            "P_cap*=4, 2SE confident deviation, canonical tie order）下，"
            "于 h2_tuning/seed 6/rep 0..9/K=10.5 的物理批上评估 B-1 样本"
            "（前 50 wait-eligible + 前 50 PM-only，cap 120）。",
            "stability (b)：ALT salt 全同（CRN 键不变，仅 salt 换）点估计 "
            ">= 0.95 为唯一硬门；Clopper-Pearson 95% 区间仅披露。",
            "stability (c)：M=8 vs M=16 离线诊断（生产 M*=8 不变）。",
            "deviation_count == 0 -> H2_NO_EFFECTIVE_DEVIATION -> DELETE；"
            "禁止为造 deviation 降低 2SE 阈值。",
            "C23：hidden（true_state/lifetime/u）变异不改变 policy "
            "decision；FULL PRODUCTION C23 在 holdout 阶段执行。",
            "C21 fail-closed + semantic evidence mapping（probe/confirm/"
            "promote/final 四段验证）。"]})

    lines = []
    for path in sorted(out_dir.rglob("*")):
        if path.is_file() and path.name != "file_hashes.sha256":
            rel = path.relative_to(out_dir).as_posix()
            lines.append(f"{_sha256_file(path)}  {rel}")
    (out_dir / "file_hashes.sha256").write_text(
        "\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def main(argv: Optional[list[str]] = None) -> int:
    output_root = BASE_DIR / "05_结果" / "H2" / "tuning" / "stability"
    run_id = _new_run_id()
    final_dir = output_root / f"run_{run_id}"
    staging_dir = BASE_DIR / ".." / "tmp" / f"p3c_staging_{run_id}"
    print(f"[p3c] run_id={run_id}")
    t0 = time.perf_counter()
    cfg = re1.RolloutConfig(batch_size=BATCH_SIZE, shift_length_h=K,
                            shifts_per_day=2, scenario="q3_two_shift",
                            tau_pm=re1.NO_PM_BEFORE_MANDATORY)
    # 1) generate the 10 tuning physical batches (H1 baseline)
    batch_logs: list[list[dict]] = []
    gen_rows = []
    for rep in REPLICATES:
        b = generate_tuning_batch(rep, cfg)
        batch_logs.append(b["events"])
        gen_rows.append({"rep": rep, "t_end": str(b["t_end"]),
                         "events": len(b["events"]),
                         "wallclock_s": round(b["wallclock_s"], 4),
                         "passed": b["passed"], "exited": b["exited"]})
    gen_wall = sum(r["wallclock_s"] for r in gen_rows)
    # 2) B-1 sample
    sample = build_b1_sample(batch_logs, K, BATCH_SIZE)
    print(f"[p3c] tuning batches: {len(batch_logs)}; sample n={sample['n']} "
          f"wait={sample['n_wait']} pm={sample['n_pm']} both={sample['n_both']}")
    # 3) stability (a): determinism via C23 hidden variants on a sample point
    c23_policy = _c23_policy_check(sample, batch_logs)
    # 4) stability (b): normal vs ALT salt
    ev_normal = evaluate_sample(sample, batch_logs, "q3h2-bootstrap-v1",
                                M_STAR, BATCH_SIZE)
    ev_alt = evaluate_sample(sample, batch_logs, ALT_SALT, M_STAR, BATCH_SIZE)
    b_res = stability_b(ev_normal, ev_alt)
    # 5) stability (c): M=8 vs M=16
    ev_m16 = evaluate_sample(sample, batch_logs, "q3h2-bootstrap-v1",
                             2 * M_STAR, BATCH_SIZE)
    c_res = stability_c(ev_normal, ev_m16)
    # 6) deviation rate
    dev_report = {"evaluated": ev_normal["n"],
                  "deviation_count": ev_normal["n_deviated"],
                  "deviation_rate": ev_normal["deviation_rate"],
                  "deviation_types": ev_normal["deviation_types"],
                  "note": "deviation_count==0 -> "
                          "H2_NO_EFFECTIVE_DEVIATION -> DELETE"}
    # 7) gates
    n_ok = sample["n"] >= 50
    b_ok = b_res["status"] == "PASS"
    c_ok = c_res["status"] == "PASS"
    dev_ok = ev_normal["n_deviated"] > 0
    c23_ok = c23_policy["status"] == "PASS"
    overall = (n_ok and b_ok and c_ok and dev_ok and c23_ok)
    if not n_ok:
        final_status = "H2_DELETE_INSUFFICIENT_STABILITY_SAMPLE"
    elif not dev_ok:
        final_status = "H2_DELETE_NO_EFFECTIVE_DEVIATION"
    elif not (b_ok and c_ok):
        final_status = "H2_DELETE_ACTION_STABILITY_FAIL"
    elif not c23_ok:
        final_status = "H2_DELETE_C23_RED"
    else:
        final_status = "PASS"
    # 8) tests + regressions
    test_report = _run_suite(PRIMARY_TEST_PATTERN)
    regressions = [_run_suite(p) for p in REGRESSION_PATTERNS]
    wall_total = time.perf_counter() - t0
    print(f"[p3c] agreement_b={b_res['agreement']:.4f} (n={b_res['n']}) "
          f"agreement_c={c_res['agreement']:.4f} (n={c_res['n']}) "
          f"dev_rate={dev_report['deviation_rate']:.4f} "
          f"final={final_status} tests={test_report['tests_run']} "
          f"regressions={[r['tests_run'] for r in regressions]}")
    # ---- budget ledger (append this run's entry) ----
    ledger_path = BASE_DIR / "05_结果" / "H2" / "dev_budget_ledger.json"
    ledger = json.loads(ledger_path.read_text(encoding="utf-8"))
    entry_ids = {e.get("entry_id") for e in ledger["entries"]}
    entry_id = f"P3-C-{run_id}"
    if entry_id not in entry_ids:
        ledger["entries"].append({
            "entry_id": entry_id,
            "task": "Q3-H2-P3-C action stability diagnostics (b)(c)",
            "run_id": run_id,
            "wall_clock_s": round(wall_total, 4),
            "status": final_status,
            "category": "stability offline diagnostics (h2_tuning rep 0..9 "
                        "K=10.5)",
            "namespace": "h2_tuning (physical worlds) / h2_rollout "
                         "(rollout keys)",
            "note": (f"sample n={sample['n']}; normal+ALT+M16; "
                     f"agreement_b={b_res['agreement']:.4f}; "
                     f"agreement_c={c_res['agreement']:.4f}; "
                     f"dev_count={dev_report['deviation_count']}"),
            "date": "2026-08-16"})
    ledger["cumulative_wall_clock_s"] = round(
        sum(e["wall_clock_s"] for e in ledger["entries"]), 4)
    ledger["cumulative_wall_clock_h"] = round(
        ledger["cumulative_wall_clock_s"] / 3600.0, 6)
    ledger["soft_budget_reached"] = (
        ledger["cumulative_wall_clock_h"] >= ledger["soft_budget_h"])
    ledger["hard_budget_reached"] = (
        ledger["cumulative_wall_clock_h"] >= ledger["hard_budget_h"])
    ledger_path.write_text(json.dumps(ledger, ensure_ascii=False,
                                      sort_keys=True, indent=1) + "\n",
                           encoding="utf-8", newline="\n")
    # ---- evidence: probe / confirm / promote / final (fail-closed) ----
    checks = {
        "overall": "PASS" if overall else "FAIL",
        "checks": [
            {"check": "B1_SAMPLE_SELECTION",
             "status": "PASS" if n_ok else "FAIL", "n": sample["n"]},
            {"check": "STABILITY_B", "status": "PASS" if b_ok else "FAIL",
             "agreement": b_res["agreement"]},
            {"check": "STABILITY_C", "status": "PASS" if c_ok else "FAIL",
             "agreement": c_res["agreement"]},
            {"check": "DEVIATION", "status": "PASS" if dev_ok else "FAIL",
             "deviation_count": dev_report["deviation_count"]},
            {"check": "C23_POLICY", "status": "PASS" if c23_ok else "FAIL"},
        ]}
    _build_evidence(staging_dir, run_id, checks, test_report, regressions,
                    None, wall_total, sample, b_res, c_res, dev_report,
                    c23_policy, ev_normal, ev_alt, ev_m16, gen_rows, gen_wall,
                    final_status)
    probe = _verify(staging_dir)
    print(f"[p3c] probe verification ok={probe.get('ok')} "
          f"{probe.get('error', '')}")
    if not probe.get("ok"):
        return 1
    _build_evidence(staging_dir, run_id, checks, test_report, regressions,
                    probe, wall_total, sample, b_res, c_res, dev_report,
                    c23_policy, ev_normal, ev_alt, ev_m16, gen_rows, gen_wall,
                    final_status)
    confirm = _verify(staging_dir)
    if not confirm.get("ok"):
        print(f"[p3c] FAIL final-content verification "
              f"{confirm.get('error', '')}")
        return 1
    promo = _promote(staging_dir, final_dir)
    if not promo["ok"]:
        print(f"[p3c] FAIL promote {promo['sha_mismatches']}")
        return 1
    final_verify = _verify(final_dir)
    ok = (probe.get("ok") and confirm.get("ok") and promo["ok"]
          and final_verify.get("ok") and checks["overall"] == "PASS"
          and test_report["ok"] and all(r["ok"] for r in regressions))
    print(f"[p3c] evidence written: {final_dir}")
    print(f"[p3c] DONE overall={'PASS' if ok else 'FAIL'} "
          f"wall={wall_total:.1f}s")
    return 0 if ok else 1


def _c23_policy_check(sample: dict, batch_logs: list[list[dict]]
                      ) -> dict[str, Any]:
    """C23 policy determinism: hidden-world variants do not change the
    policy action at a sample point."""
    failures = []
    if not sample["points"]:
        return {"check": "C23_POLICY", "status": "FAIL",
                "failures": ["empty sample"]}
    p = sample["points"][0]
    blog = batch_logs[p["batch"]]
    # variant logs with different hidden annotations
    variants = []
    for i, mut in enumerate((lambda r: r.update(true_state={"A": True, "B": True, "C": True}),
                             lambda r: r.update(lifetime_h="999"),
                             lambda r: r.update(u="0.999"))):
        vlog = []
        for r in blog:
            rec = dict(r)
            mut(rec)
            vlog.append(rec)
        variants.append(vlog)
    chosen = []
    for vlog in [blog] + variants:
        ctx = _point_context(p, vlog, BATCH_SIZE)
        dec = pol.evaluate_decision_point(
            ctx["state"], ctx["posterior"], ctx["world"], ctx["provider"],
            ctx["cfg"], p["dp"], p["resource"], p["kind"],
            p["quota_class"], tuple(p["legal_actions"]), ctx["log_prefix"],
            MASTER_SEED, p["batch"], wait_anchor_time=p.get("wait_anchor_time"),
            M=4)  # small M for the C23 determinism check
        chosen.append(dec.chosen)
    if len(set(chosen)) != 1:
        failures.append(f"hidden variants changed the action: {chosen}")
    return {"check": "C23_POLICY", "status": "PASS" if not failures else "FAIL",
            "failures": failures, "actions_by_variant": chosen}


if __name__ == "__main__":
    sys.exit(main())
