#!/usr/bin/env python3
"""Q3-H2-P3-C H2 policy batch driver (SPEC 2/4/5/6/10/13, frozen).

Runs a full batch (physical world under an H2 namespace: h2_tuning /
h2_holdout) with the FINAL H2 policy applied at quota-selected decision
points:

  * the physical world is generated by the continuation engine consuming
    the *post* streams under the batch namespace (h2_tuning / h2_holdout)
    via ``physical_post_provider`` (the accepted legacy engine rejects H2
    namespaces; the batch driver is the h2-side world generator);
  * at each same-timestamp closure, after releases and BEFORE the engine's
    H1 dispatch, the driver reconstructs the decision points at t, applies
    the ONLINE quota selector (C_eval*=8, W_cap*=4, P_cap*=4), and for each
    selected point evaluates the frozen H2 policy (M=8 rollouts under
    h2_rollout keys, 2SE confident deviation, a_H1 by point class);
  * the chosen action is injected: START_HEAD / H1_NOOP -> the engine's own
    dispatch proceeds (H1 default); WAIT_EVENT -> the resource is held
    (skipped by dispatch) until the anchor; PM_WITH_HEAD / PM_IDLE ->
    replacement pending set (engine replaces + calibrates first);
  * C_rollout (<=200/batch) is counted as SUM over selected points of
    (candidate actions x M); violations are hard FAIL.

Decision logs (SPEC 17.2): per-batch decision log rows with dp / type /
quota class / candidates (incl. a_H1) / Q_hat / SE / chosen action /
rollout count.  state_hash = canonical ObservableState fingerprint.

Python 3.12, standard library only.
"""
from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from fractions import Fraction
from typing import Any, Callable, Optional

from main_model.h2 import observable_state_v1 as obs  # noqa: E402
from main_model.h2 import posterior_state_v1 as ps  # noqa: E402
from main_model.h2 import continuation_v1 as cont  # noqa: E402
from main_model.h2 import decision_point_v1 as dpimpl  # noqa: E402
from main_model.h2 import quota_selector_v1 as qsel  # noqa: E402
from main_model.h2_rollout import rollout_engine_v1 as re1  # noqa: E402
from main_model.h2_rollout import h2_policy_v1 as pol  # noqa: E402


@dataclass
class BatchDecisionLog:
    """One batch's decision-log rows + rollout accounting."""
    rows: list[dict[str, Any]] = field(default_factory=list)
    n_selected: int = 0
    n_deviated: int = 0
    rollout_count: int = 0
    wait_selected: int = 0
    pm_selected: int = 0


class H2BatchRunner(re1.RolloutEngine):
    """RolloutEngine subclass that applies the frozen H2 policy online."""

    def __init__(self, state: obs.ObservableState,
                 posterior: ps.PosteriorState,
                 world: cont.ContinuationWorld,
                 provider: re1.PostKeyProvider,
                 config: re1.RolloutConfig,
                 log_prefix: Optional[list[dict[str, Any]]],
                 master_seed_h2: int,
                 batch_replicate_id: int,
                 c_eval: int = pol.C_EVAL_STAR,
                 M: int = pol.M_STAR,
                 policy_enabled: bool = True,
                 decision_log: Optional[BatchDecisionLog] = None) -> None:
        # A FRESH batch has no observable history: the engine log must still
        # record the preloaded devices' entries (TRUE_STATE_GENERATED at
        # entry time) plus the opening shift change, exactly like the
        # accepted engine's init -- otherwise every later observable
        # projection sees an empty device set while queues already reference
        # devices 1..N (KeyError in policy rollouts / decision
        # reconstruction).  When the caller supplies a log_prefix (rebuild
        # from an existing history) we keep it verbatim.
        if log_prefix is None:
            log_prefix = [
                {"event_type": "TRUE_STATE_GENERATED",
                 "event_time": str(state.time),
                 "device_id": d.device_id,
                 "true_state": {"A": False, "B": False, "C": False}}
                for d in sorted(state.devices,
                                key=lambda dd: dd.device_id)]
            sh = obs.active_shift(obs.q3_shift_grid(config.shift_length_h),
                                  state.time)
            if sh is None:
                sh = state.active_shift
            if sh is not None:
                log_prefix.append({
                    "event_type": "SHIFT_CHANGE", "event_time": str(state.time),
                    "shift_index": state.shift_index if state.shift_index
                    is not None else 0,
                    "shift_start": str(sh[0]), "shift_end": str(sh[1]),
                    "on_duty_squad": state.on_duty_squad
                    if state.on_duty_squad is not None else 0,
                    "squad_id": state.on_duty_squad
                    if state.on_duty_squad is not None else 0})
        super().__init__(state, posterior, world, provider, config,
                         first_action=re1.A_H1_NOOP, log_prefix=log_prefix)
        self.master_seed_h2 = master_seed_h2
        self.batch_replicate_id = batch_replicate_id
        self.c_eval = c_eval
        self.M = M
        self.policy_enabled = policy_enabled
        self.quota_state = qsel.QuotaState(c_eval)
        self.wait_holds: dict[str, Fraction] = {}  # resource -> anchor
        self.decision_log = decision_log if decision_log is not None \
            else BatchDecisionLog()
        self._c_rollout = 0
        self.K = config.shift_length_h

    # -- policy injection ------------------------------------------------

    def _h2_step(self, t: Fraction) -> None:
        """Reconstruct decision points at t, apply the online quota, evaluate
        the policy, and inject the chosen actions."""
        if not self.policy_enabled:
            return
        # clear expired wait holds
        for r in [r for r, a in self.wait_holds.items() if t >= a]:
            del self.wait_holds[r]
        # reconstruct decision points at this closure
        pts = dpimpl.reconstruct_decision_points(
            list(self.log), self.K, batch_size=self.config.batch_size,
            t_end=t + Fraction(1, 1000000))
        at_t = [p for p in pts if p.time == t]
        if not at_t:
            return
        # project the PRE-ACTION observable state at t (decision boundary:
        # same-timestamp dispatch records excluded; REQUALIFIED P3 decision
        # semantics, identical to the offline decision-point reconstruction)
        st = dpimpl.project_pre_action_state(
            list(self.log), t, batch_size=self.config.batch_size)
        pre_log = dpimpl.pre_action_log(list(self.log), t)
        post = ps.PosteriorState.from_observable(st)
        gen = {r.resource: r.generation for r in st.resources}
        # map decision points to quota events (online, in time order)
        events = []
        for p in at_t:
            wait_legal = dpimpl.A_WAIT_EVENT in p.legal_actions
            pm_legal = (dpimpl.A_PM_WITH_HEAD in p.legal_actions
                        or dpimpl.A_PM_IDLE in p.legal_actions)
            rsrc = next(r for r in st.resources if r.resource == p.resource)
            events.append(qsel.DecisionPointEvent(
                dp=p.dp, time=p.time, resource=p.resource, kind=p.kind,
                wait_legal=wait_legal, pm_legal=pm_legal, age_h=rsrc.age_h,
                head=p.head))
        # process each event in deterministic order (resource order is
        # already canonical A/B/C/E within a closure)
        pt_by_res = {p.resource: p for p in at_t}
        for ev in events:
            # dp = monotonic per-batch index of this H2-eligible point
            # (reconstruct_decision_points re-enumerates from 0 at each
            # closure, so the quota selector must use a stable batch-level
            # index; SPEC 6.2: dp = 本批内已评估 H2 决策点序号).
            ev = qsel.DecisionPointEvent(
                dp=len(self.decision_log.rows), time=ev.time,
                resource=ev.resource, kind=ev.kind,
                wait_legal=ev.wait_legal, pm_legal=ev.pm_legal,
                age_h=ev.age_h, head=ev.head)
            sel, cls, self.quota_state = qsel.select_point(
                self.quota_state, ev)
            if not sel:
                continue
            p = pt_by_res[ev.resource]
            legal = tuple(p.legal_actions)
            wait_anchor = (p.wait_anchor.completion_time
                           if p.wait_anchor is not None else None)
            # policy evaluation rebuilds its OWN posterior world_m per m
            # from the h2_rollout post keys (second requalification: no
            # fixed physical/dummy world enters the rollouts; x_abc / x_d /
            # residual lifetimes are resampled from the rollout keys only)
            dec = pol.evaluate_decision_point(
                st, post, self.config,
                ev.dp, ev.resource, ev.kind, cls, legal,
                pre_log, self.master_seed_h2, self.batch_replicate_id,
                wait_anchor_time=wait_anchor, M=self.M,
                decision_head=ev.head)
            self._c_rollout += len(dec.legal_actions) * self.M
            self.decision_log.rollout_count += len(dec.legal_actions) * self.M
            self.decision_log.n_selected += 1
            if dec.deviated:
                self.decision_log.n_deviated += 1
            if cls == qsel.WAIT_CLASS:
                self.decision_log.wait_selected += 1
            else:
                self.decision_log.pm_selected += 1
            row = dec.to_canonical_dict()
            row["state_hash"] = st.fingerprint()
            row["rollout_count"] = len(dec.legal_actions) * self.M
            self.decision_log.rows.append(row)
            # inject the chosen action
            if dec.chosen == re1.A_WAIT_EVENT and wait_anchor is not None:
                self.wait_holds[ev.resource] = wait_anchor
            elif dec.chosen in (re1.A_PM_WITH_HEAD, re1.A_PM_IDLE):
                self._set_replacement_pending(ev.resource, "preventive",
                                              "h2_pm")
            # START_HEAD / H1_NOOP: engine's own dispatch proceeds

    def _resources(self) -> tuple[str, ...]:
        return tuple(r.resource_id for r in self.resources.values())

    # -- engine integration: hold dispatch for WAIT -----------------------

    def _equipment_and_dispatch(self) -> None:
        # resources under a WAIT hold stay idle until the anchor: the hold
        # is enforced via _is_legal (the engine's dispatch checks legality
        # of each head before starting).
        super()._equipment_and_dispatch()

    def _is_legal(self, entry: re1._QueueEntry) -> bool:
        if not super()._is_legal(entry):
            return False
        task = self.tasks[entry.task_id]
        if task.resource_id in self.wait_holds:
            return False  # WAIT_EVENT hold: do not start until the anchor
        return True

    # -- run with per-closure policy --------------------------------------

    def run(self) -> re1.RolloutResult:
        self._apply_first_action_if_dispatch()
        self._closure(self.now)
        while True:
            if self._is_terminal():
                self._record("SIMULATION_END")
                break
            nxt = self._next_event_time()
            if nxt <= self.now:
                raise RuntimeError(f"no progress: next event {nxt} <= now "
                                   f"{self.now}")
            self._closure(nxt)
        return re1.RolloutResult(
            t_end=self.now, events=tuple(self.log),
            consumed_u_y=self.consumed_u_y, consumed_u_d=self.consumed_u_d,
            consumed_u_l=self.consumed_u_l,
            replacements=sum(e.replacement_count
                             for e in self.equipment.values()),
            devices_passed=sum(1 for d in self.devices.values()
                               if d.terminal_state == "PASSED"),
            devices_exited=sum(1 for d in self.devices.values()
                               if d.terminal_state == "EXITED"),
        )

    # -- closure override: insert the policy step before dispatch ---------

    def _closure(self, t: Fraction) -> None:
        self.now = t
        completed, failed, illegal, calib_done, turnover_out, turnover_in = (
            self._settle(t))
        self._observe(completed)
        self._classify(completed)
        exit_devices = self._apply_exits(completed)
        self._cancel_unfinished(exit_devices)
        self._materialize_d()
        self._shift_change()
        self._release_tasks()
        self._h2_step(t)
        self._equipment_and_dispatch()
        self._start_turnovers()
